/* Net ACM_signals - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <string.h>
#include "net_types.h"


#define ABS(x) (((x)>=0)?(x):-(x))


/* Array implementation: */


void createInitial_ACM_signals_NetMarking( ACM_signals_NetMarking* init_marking )
{
    memset( init_marking, 0, sizeof(*init_marking) );
    init_marking->p_306 = 0; /* Place tpi_inChg */
    init_marking->p_308 = 1; /* Place joy_inChg */
    init_marking->p_386 = 0; /* Place Left */
    init_marking->p_387 = 0; /* Place Backward */
    init_marking->p_448 = 0; /* Place left_side */
    init_marking->p_495 = 0; /* Place horn_ON_button */
    init_marking->p_496 = 1; /* Place horn_OFF */
    init_marking->p_502 = 1; /* Place speed_25 */
    init_marking->p_503 = 0; /* Place speed_50 */
    init_marking->p_504 = 0; /* Place speed_75 */
    init_marking->p_505 = 0; /* Place speed_100 */
    init_marking->p_545 = 1; /* Place back_0 */
    init_marking->p_546 = 0; /* Place back_1 */
    init_marking->p_547 = 0; /* Place back_2 */
    init_marking->p_548 = 0; /* Place back_3 */
    init_marking->p_567 = 1; /* Place left_0 */
    init_marking->p_568 = 0; /* Place left_1 */
    init_marking->p_569 = 0; /* Place left_2 */
    init_marking->p_570 = 0; /* Place left_3 */
    init_marking->p_589 = 1; /* Place right_0 */
    init_marking->p_590 = 0; /* Place right_1 */
    init_marking->p_591 = 0; /* Place right_2 */
    init_marking->p_592 = 0; /* Place right_3 */
    init_marking->p_611 = 1; /* Place front_flat */
    init_marking->p_612 = 0; /* Place front_step */
    init_marking->p_634 = 0; /* Place Assist_mode_ON */
    init_marking->p_635 = 1; /* Place Assist_mode_OFF */
    init_marking->p_697 = 0; /* Place back_side */
    init_marking->p_710 = 0; /* Place Forward */
    init_marking->p_714 = 0; /* Place front_side */
    init_marking->p_726 = 0; /* Place Right */
    init_marking->p_729 = 0; /* Place right_side */
    init_marking->p_822 = 1; /* Place leveled */
    init_marking->p_823 = 0; /* Place tilted_up_1 */
    init_marking->p_835 = 0; /* Place tilted_up_2 */
    init_marking->p_842 = 0; /* Place tilted_up_3 */
    init_marking->p_849 = 0; /* Place tilted_down_1 */
    init_marking->p_852 = 0; /* Place tilted_down_2 */
    init_marking->p_855 = 0; /* Place tilted_down_3 */
}

void createEmpty_ACM_signals_NetMarking( ACM_signals_NetMarking* empty_marking )
{
    empty_marking->p_306 = 0; /* Place tpi_inChg */
    empty_marking->p_308 = 0; /* Place joy_inChg */
    empty_marking->p_386 = 0; /* Place Left */
    empty_marking->p_387 = 0; /* Place Backward */
    empty_marking->p_448 = 0; /* Place left_side */
    empty_marking->p_495 = 0; /* Place horn_ON_button */
    empty_marking->p_496 = 0; /* Place horn_OFF */
    empty_marking->p_502 = 0; /* Place speed_25 */
    empty_marking->p_503 = 0; /* Place speed_50 */
    empty_marking->p_504 = 0; /* Place speed_75 */
    empty_marking->p_505 = 0; /* Place speed_100 */
    empty_marking->p_545 = 0; /* Place back_0 */
    empty_marking->p_546 = 0; /* Place back_1 */
    empty_marking->p_547 = 0; /* Place back_2 */
    empty_marking->p_548 = 0; /* Place back_3 */
    empty_marking->p_567 = 0; /* Place left_0 */
    empty_marking->p_568 = 0; /* Place left_1 */
    empty_marking->p_569 = 0; /* Place left_2 */
    empty_marking->p_570 = 0; /* Place left_3 */
    empty_marking->p_589 = 0; /* Place right_0 */
    empty_marking->p_590 = 0; /* Place right_1 */
    empty_marking->p_591 = 0; /* Place right_2 */
    empty_marking->p_592 = 0; /* Place right_3 */
    empty_marking->p_611 = 0; /* Place front_flat */
    empty_marking->p_612 = 0; /* Place front_step */
    empty_marking->p_634 = 0; /* Place Assist_mode_ON */
    empty_marking->p_635 = 0; /* Place Assist_mode_OFF */
    empty_marking->p_697 = 0; /* Place back_side */
    empty_marking->p_710 = 0; /* Place Forward */
    empty_marking->p_714 = 0; /* Place front_side */
    empty_marking->p_726 = 0; /* Place Right */
    empty_marking->p_729 = 0; /* Place right_side */
    empty_marking->p_822 = 0; /* Place leveled */
    empty_marking->p_823 = 0; /* Place tilted_up_1 */
    empty_marking->p_835 = 0; /* Place tilted_up_2 */
    empty_marking->p_842 = 0; /* Place tilted_up_3 */
    empty_marking->p_849 = 0; /* Place tilted_down_1 */
    empty_marking->p_852 = 0; /* Place tilted_down_2 */
    empty_marking->p_855 = 0; /* Place tilted_down_3 */
}

void add_ACM_signals_NetMarkings(
    ACM_signals_NetMarking* dest_marking,
    ACM_signals_NetMarking* source_marking )
{
    dest_marking->p_306 += source_marking->p_306; /* Place tpi_inChg */
    dest_marking->p_308 += source_marking->p_308; /* Place joy_inChg */
    dest_marking->p_386 += source_marking->p_386; /* Place Left */
    dest_marking->p_387 += source_marking->p_387; /* Place Backward */
    dest_marking->p_448 += source_marking->p_448; /* Place left_side */
    dest_marking->p_495 += source_marking->p_495; /* Place horn_ON_button */
    dest_marking->p_496 += source_marking->p_496; /* Place horn_OFF */
    dest_marking->p_502 += source_marking->p_502; /* Place speed_25 */
    dest_marking->p_503 += source_marking->p_503; /* Place speed_50 */
    dest_marking->p_504 += source_marking->p_504; /* Place speed_75 */
    dest_marking->p_505 += source_marking->p_505; /* Place speed_100 */
    dest_marking->p_545 += source_marking->p_545; /* Place back_0 */
    dest_marking->p_546 += source_marking->p_546; /* Place back_1 */
    dest_marking->p_547 += source_marking->p_547; /* Place back_2 */
    dest_marking->p_548 += source_marking->p_548; /* Place back_3 */
    dest_marking->p_567 += source_marking->p_567; /* Place left_0 */
    dest_marking->p_568 += source_marking->p_568; /* Place left_1 */
    dest_marking->p_569 += source_marking->p_569; /* Place left_2 */
    dest_marking->p_570 += source_marking->p_570; /* Place left_3 */
    dest_marking->p_589 += source_marking->p_589; /* Place right_0 */
    dest_marking->p_590 += source_marking->p_590; /* Place right_1 */
    dest_marking->p_591 += source_marking->p_591; /* Place right_2 */
    dest_marking->p_592 += source_marking->p_592; /* Place right_3 */
    dest_marking->p_611 += source_marking->p_611; /* Place front_flat */
    dest_marking->p_612 += source_marking->p_612; /* Place front_step */
    dest_marking->p_634 += source_marking->p_634; /* Place Assist_mode_ON */
    dest_marking->p_635 += source_marking->p_635; /* Place Assist_mode_OFF */
    dest_marking->p_697 += source_marking->p_697; /* Place back_side */
    dest_marking->p_710 += source_marking->p_710; /* Place Forward */
    dest_marking->p_714 += source_marking->p_714; /* Place front_side */
    dest_marking->p_726 += source_marking->p_726; /* Place Right */
    dest_marking->p_729 += source_marking->p_729; /* Place right_side */
    dest_marking->p_822 += source_marking->p_822; /* Place leveled */
    dest_marking->p_823 += source_marking->p_823; /* Place tilted_up_1 */
    dest_marking->p_835 += source_marking->p_835; /* Place tilted_up_2 */
    dest_marking->p_842 += source_marking->p_842; /* Place tilted_up_3 */
    dest_marking->p_849 += source_marking->p_849; /* Place tilted_down_1 */
    dest_marking->p_852 += source_marking->p_852; /* Place tilted_down_2 */
    dest_marking->p_855 += source_marking->p_855; /* Place tilted_down_3 */
}

void init_ACM_signals_OutputSignals(
    ACM_signals_PlaceOutputSignals* place_out,
    ACM_signals_EventOutputSignals* ev_out )
{
    memset( place_out, 0, sizeof(*place_out) );
    memset( ev_out, 0, sizeof(*ev_out) );
    place_out->tpi_inChg = 0;
    place_out->ForwardQ = 1;
    place_out->ReverseQ = 1;
    place_out->RightQ = 1;
    place_out->LeftQ = 1;
    place_out->Horn = 0;
    place_out->speedDial = 0;
    place_out->back_alert = 0;
    place_out->left_alert = 0;
    place_out->right_alert = 0;
    place_out->front_alert = 0;
    place_out->Assist_mode = 0;
    place_out->pitch_alert = 0;
}

/* Transition 305 - change_Joy */
int t_305_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_306 >= 1 && avail->p_448 >= 1 && avail->p_697 >= 1 && avail->p_714 >= 1 && avail->p_729 >= 1 );
}

int t_305_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_305_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->inChg != 0 );
}

void t_305_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_306--;
    marking->p_448--;
    marking->p_697--;
    marking->p_714--;
    marking->p_729--;
}

void t_305_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_308++;
}

void t_305_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 322 - change_TPI */
int t_322_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_308 >= 1 );
}

int t_322_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_322_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->inChg == 0 );
}

void t_322_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_308--;
}

void t_322_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_306++;
    marking->p_448++;
    marking->p_697++;
    marking->p_714++;
    marking->p_729++;
}

void t_322_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 398 - stop_RightON */
int t_398_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_386 >= 1 );
}

int t_398_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_398_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( inputs->btnR || inputs->btnF_R || inputs->btnB_R ) == 1 );
}

void t_398_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_386--;
}

void t_398_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_448++;
}

void t_398_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 473 - stop_FrontON */
int t_473_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_387 >= 1 );
}

int t_473_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_473_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( inputs->btnF || inputs->btnF_R || inputs->btnF_L ) == 1 );
}

void t_473_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_387--;
}

void t_473_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_697++;
}

void t_473_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 482 - stop_LeftOFF */
int t_482_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_386 >= 1 );
}

int t_482_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_482_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( inputs->btnL || inputs->btnF_L || inputs->btnB_L ) == 0 );
}

void t_482_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_386--;
}

void t_482_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_448++;
}

void t_482_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 485 - stop_BackOFF */
int t_485_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_387 >= 1 );
}

int t_485_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_485_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( inputs->btnB || inputs->btnB_R || inputs->btnB_L ) == 0 );
}

void t_485_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_387--;
}

void t_485_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_697++;
}

void t_485_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 494 - horn_OFF */
int t_494_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_495 >= 1 );
}

int t_494_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_494_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->btnHorn == 0 && ( place_out->front_alert == 0 && place_out->back_alert != 3 && place_out->left_alert != 3 && place_out->right_alert != 3 ) );
}

void t_494_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_495--;
}

void t_494_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_496++;
}

void t_494_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 497 - horn_ON */
int t_497_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_496 >= 1 );
}

int t_497_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_497_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->btnHorn == 1 && place_out->tpi_inChg == 1 );
}

void t_497_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_496--;
}

void t_497_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_495++;
}

void t_497_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 506 - increase */
int t_506_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_502 >= 1 );
}

int t_506_events( ACM_signals_InputSignalEvents* events )
{
    return ( events->btnInc_up );
}

int t_506_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->tpi_inChg == 1 );
}

void t_506_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_502--;
}

void t_506_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_503++;
}

void t_506_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 507 - decrease */
int t_507_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_503 >= 1 );
}

int t_507_events( ACM_signals_InputSignalEvents* events )
{
    return ( events->btnDec_up );
}

int t_507_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->tpi_inChg == 1 );
}

void t_507_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_503--;
}

void t_507_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_502++;
}

void t_507_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 508 - decrease_2 */
int t_508_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_504 >= 1 );
}

int t_508_events( ACM_signals_InputSignalEvents* events )
{
    return ( events->btnDec_up );
}

int t_508_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->tpi_inChg == 1 );
}

void t_508_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_504--;
}

void t_508_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_503++;
}

void t_508_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 509 - increase_2 */
int t_509_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_503 >= 1 );
}

int t_509_events( ACM_signals_InputSignalEvents* events )
{
    return ( events->btnInc_up );
}

int t_509_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->tpi_inChg == 1 );
}

void t_509_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_503--;
}

void t_509_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_504++;
}

void t_509_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 510 - decrease_3 */
int t_510_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_505 >= 1 );
}

int t_510_events( ACM_signals_InputSignalEvents* events )
{
    return ( events->btnDec_up );
}

int t_510_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->tpi_inChg == 1 );
}

void t_510_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_505--;
}

void t_510_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_504++;
}

void t_510_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 511 - increase_3 */
int t_511_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_504 >= 1 );
}

int t_511_events( ACM_signals_InputSignalEvents* events )
{
    return ( events->btnInc_up );
}

int t_511_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->tpi_inChg == 1 );
}

void t_511_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_504--;
}

void t_511_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_505++;
}

void t_511_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 549 - closer */
int t_549_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_545 >= 1 );
}

int t_549_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_549_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->back_sensor_dist <= ( inputs->dist_min * 3 ) );
}

void t_549_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_545--;
}

void t_549_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_546++;
}

void t_549_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 550 - further */
int t_550_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_546 >= 1 );
}

int t_550_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_550_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->back_sensor_dist > ( inputs->dist_min * 3 ) );
}

void t_550_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_546--;
}

void t_550_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_545++;
}

void t_550_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 551 - further */
int t_551_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_547 >= 1 );
}

int t_551_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_551_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->back_sensor_dist > ( inputs->dist_min * 2 ) );
}

void t_551_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_547--;
}

void t_551_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_546++;
}

void t_551_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 552 - closer */
int t_552_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_546 >= 1 );
}

int t_552_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_552_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->back_sensor_dist <= ( inputs->dist_min * 2 ) );
}

void t_552_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_546--;
}

void t_552_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_547++;
}

void t_552_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 553 - further */
int t_553_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_548 >= 1 );
}

int t_553_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_553_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->back_sensor_dist > inputs->dist_min );
}

void t_553_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_548--;
}

void t_553_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_547++;
}

void t_553_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 554 - closer */
int t_554_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_547 >= 1 );
}

int t_554_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_554_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->back_sensor_dist <= inputs->dist_min );
}

void t_554_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_547--;
}

void t_554_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_548++;
}

void t_554_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 571 - closer_2 */
int t_571_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_567 >= 1 );
}

int t_571_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_571_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->left_sensor_dist <= ( inputs->dist_min * 3 ) );
}

void t_571_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_567--;
}

void t_571_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_568++;
}

void t_571_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 572 - further_2 */
int t_572_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_568 >= 1 );
}

int t_572_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_572_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->left_sensor_dist > ( inputs->dist_min * 3 ) );
}

void t_572_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_568--;
}

void t_572_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_567++;
}

void t_572_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 573 - further_3 */
int t_573_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_569 >= 1 );
}

int t_573_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_573_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->left_sensor_dist > ( inputs->dist_min * 2 ) );
}

void t_573_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_569--;
}

void t_573_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_568++;
}

void t_573_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 574 - closer_3 */
int t_574_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_568 >= 1 );
}

int t_574_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_574_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->left_sensor_dist <= ( inputs->dist_min * 2 ) );
}

void t_574_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_568--;
}

void t_574_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_569++;
}

void t_574_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 575 - further_4 */
int t_575_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_570 >= 1 );
}

int t_575_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_575_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->left_sensor_dist > inputs->dist_min );
}

void t_575_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_570--;
}

void t_575_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_569++;
}

void t_575_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 576 - closer_4 */
int t_576_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_569 >= 1 );
}

int t_576_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_576_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->left_sensor_dist <= inputs->dist_min );
}

void t_576_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_569--;
}

void t_576_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_570++;
}

void t_576_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 593 - closer_5 */
int t_593_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_589 >= 1 );
}

int t_593_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_593_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->right_sensor_dist <= ( inputs->dist_min * 3 ) );
}

void t_593_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_589--;
}

void t_593_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_590++;
}

void t_593_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 594 - further_5 */
int t_594_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_590 >= 1 );
}

int t_594_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_594_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->right_sensor_dist > ( inputs->dist_min * 3 ) );
}

void t_594_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_590--;
}

void t_594_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_589++;
}

void t_594_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 595 - further_6 */
int t_595_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_591 >= 1 );
}

int t_595_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_595_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->right_sensor_dist > ( inputs->dist_min * 2 ) );
}

void t_595_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_591--;
}

void t_595_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_590++;
}

void t_595_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 596 - closer_6 */
int t_596_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_590 >= 1 );
}

int t_596_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_596_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->right_sensor_dist <= ( inputs->dist_min * 2 ) );
}

void t_596_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_590--;
}

void t_596_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_591++;
}

void t_596_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 597 - further_7 */
int t_597_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_592 >= 1 );
}

int t_597_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_597_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->right_sensor_dist > inputs->dist_min );
}

void t_597_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_592--;
}

void t_597_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_591++;
}

void t_597_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 598 - closer_7 */
int t_598_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_591 >= 1 );
}

int t_598_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_598_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->right_sensor_dist <= inputs->dist_min );
}

void t_598_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_591--;
}

void t_598_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_592++;
}

void t_598_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 615 - step_detect */
int t_615_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_611 >= 1 );
}

int t_615_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_615_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->front_sensor_dist >= 35 );
}

void t_615_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_611--;
}

void t_615_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_612++;
}

void t_615_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 616 - no_step */
int t_616_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_612 >= 1 );
}

int t_616_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_616_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->front_sensor_dist < 35 );
}

void t_616_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_612--;
}

void t_616_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_611++;
}

void t_616_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 643 - change_ON */
int t_643_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_635 >= 1 );
}

int t_643_events( ACM_signals_InputSignalEvents* events )
{
    return ( events->btnAssist_mode_up );
}

int t_643_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->tpi_inChg == 1 );
}

void t_643_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_635--;
}

void t_643_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_634++;
}

void t_643_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 651 - change_joyInChg */
int t_651_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_634 >= 1 );
}

int t_651_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_651_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->tpi_inChg == 0 );
}

void t_651_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_634--;
}

void t_651_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_635++;
}

void t_651_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 652 - change_OFF */
int t_652_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_634 >= 1 );
}

int t_652_events( ACM_signals_InputSignalEvents* events )
{
    return ( events->btnAssist_mode_up );
}

int t_652_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_652_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_634--;
}

void t_652_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_635++;
}

void t_652_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 673 - step_control */
int t_673_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_710 >= 1 );
}

int t_673_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_673_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->front_alert == 1 && place_out->Assist_mode == 1 );
}

void t_673_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_710--;
}

void t_673_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_714++;
}

void t_673_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 685 - stop_joyInChg */
int t_685_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_386 >= 1 );
}

int t_685_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_685_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->inChg != 0 );
}

void t_685_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_386--;
}

void t_685_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_448++;
}

void t_685_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 686 - stop_joyInChg */
int t_686_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_387 >= 1 );
}

int t_686_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_686_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->inChg != 0 );
}

void t_686_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_387--;
}

void t_686_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_697++;
}

void t_686_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 694 - obstacle_control */
int t_694_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_387 >= 1 );
}

int t_694_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_694_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( place_out->back_alert == 3 || place_out->left_alert == 3 || place_out->right_alert == 3 ) && place_out->Assist_mode == 1 );
}

void t_694_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_387--;
}

void t_694_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_697++;
}

void t_694_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 707 - move_B */
int t_707_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_697 >= 1 );
}

int t_707_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_707_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( inputs->btnB || inputs->btnB_R || inputs->btnB_L ) && !( inputs->btnF || inputs->btnF_R || inputs->btnF_L ) && !( ( inputs->btnL || inputs->btnF_L || inputs->btnB_L ) && ( inputs->btnR || inputs->btnF_R || inputs->btnB_R ) ) && !( ( place_out->back_alert == 3 || place_out->left_alert == 3 || place_out->right_alert == 3 ) && place_out->Assist_mode == 1 ) );
}

void t_707_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_697--;
}

void t_707_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_387++;
}

void t_707_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 711 - stop_BackON */
int t_711_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_710 >= 1 );
}

int t_711_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_711_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( inputs->btnB || inputs->btnB_R || inputs->btnB_L ) == 1 );
}

void t_711_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_710--;
}

void t_711_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_714++;
}

void t_711_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 712 - stop_FrontOFF */
int t_712_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_710 >= 1 );
}

int t_712_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_712_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( inputs->btnF || inputs->btnF_R || inputs->btnF_L ) == 0 );
}

void t_712_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_710--;
}

void t_712_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_714++;
}

void t_712_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 713 - stop_joyInChg */
int t_713_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_710 >= 1 );
}

int t_713_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_713_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->inChg != 0 );
}

void t_713_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_710--;
}

void t_713_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_714++;
}

void t_713_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 728 - stop_LeftON */
int t_728_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_726 >= 1 );
}

int t_728_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_728_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( inputs->btnL || inputs->btnF_L || inputs->btnB_L ) == 1 );
}

void t_728_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_726--;
}

void t_728_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_729++;
}

void t_728_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 730 - stop_RightOFF */
int t_730_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_726 >= 1 );
}

int t_730_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_730_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( inputs->btnR || inputs->btnF_R || inputs->btnB_R ) == 0 );
}

void t_730_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_726--;
}

void t_730_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_729++;
}

void t_730_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 731 - stop_joyInChg */
int t_731_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_726 >= 1 );
}

int t_731_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_731_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->inChg != 0 );
}

void t_731_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_726--;
}

void t_731_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_729++;
}

void t_731_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 742 - move_R */
int t_742_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_729 >= 1 );
}

int t_742_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_742_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( ( inputs->btnR && !( place_out->left_alert == 3 && place_out->Assist_mode == 1 ) ) || ( inputs->btnB_R && !( ( place_out->back_alert == 3 || place_out->left_alert == 3 || place_out->right_alert == 3 ) && place_out->Assist_mode == 1 ) ) || ( inputs->btnF_R && !( place_out->front_alert == 1 && place_out->Assist_mode == 1 ) ) ) && !( inputs->btnL || inputs->btnF_L || inputs->btnB_L ) && !( ( inputs->btnF || inputs->btnF_R || inputs->btnF_L ) && ( inputs->btnB || inputs->btnB_R || inputs->btnB_L ) ) );
}

void t_742_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_729--;
}

void t_742_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_726++;
}

void t_742_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 745 - stop_FrontBackON */
int t_745_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_726 >= 1 );
}

int t_745_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_745_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( inputs->btnF || inputs->btnF_R || inputs->btnF_L ) && ( inputs->btnB || inputs->btnB_R || inputs->btnB_L ) );
}

void t_745_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_726--;
}

void t_745_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_729++;
}

void t_745_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 746 - stop_FrontBackON */
int t_746_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_386 >= 1 );
}

int t_746_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_746_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( inputs->btnF || inputs->btnF_R || inputs->btnF_L ) && ( inputs->btnB || inputs->btnB_R || inputs->btnB_L ) );
}

void t_746_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_386--;
}

void t_746_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_448++;
}

void t_746_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 752 - stop_LeftRightON */
int t_752_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_387 >= 1 );
}

int t_752_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_752_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( inputs->btnL || inputs->btnF_L || inputs->btnB_L ) && ( inputs->btnR || inputs->btnF_R || inputs->btnB_R ) );
}

void t_752_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_387--;
}

void t_752_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_697++;
}

void t_752_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 757 - stop_LeftRightON */
int t_757_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_710 >= 1 );
}

int t_757_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_757_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( inputs->btnL || inputs->btnF_L || inputs->btnB_L ) && ( inputs->btnR || inputs->btnF_R || inputs->btnB_R ) );
}

void t_757_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_710--;
}

void t_757_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_714++;
}

void t_757_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 765 - step_control */
int t_765_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_726 >= 1 );
}

int t_765_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_765_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->front_alert == 1 && place_out->Assist_mode == 1 && inputs->btnF_R == 1 );
}

void t_765_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_726--;
}

void t_765_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_729++;
}

void t_765_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 768 - step_control */
int t_768_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_386 >= 1 );
}

int t_768_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_768_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->front_alert == 1 && place_out->Assist_mode == 1 && inputs->btnF_L == 1 );
}

void t_768_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_386--;
}

void t_768_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_448++;
}

void t_768_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 771 - move_F */
int t_771_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_714 >= 1 );
}

int t_771_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_771_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( inputs->btnF || inputs->btnF_R || inputs->btnF_L ) && !( inputs->btnB || inputs->btnB_R || inputs->btnB_L ) && !( ( inputs->btnL || inputs->btnF_L || inputs->btnB_L ) && ( inputs->btnR || inputs->btnF_R || inputs->btnB_R ) ) && !( place_out->front_alert == 1 && place_out->Assist_mode == 1 ) );
}

void t_771_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_714--;
}

void t_771_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_710++;
}

void t_771_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 777 - move_L */
int t_777_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_448 >= 1 );
}

int t_777_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_777_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( ( inputs->btnL && !( place_out->right_alert == 3 && place_out->Assist_mode == 1 ) ) || ( inputs->btnB_L && !( ( place_out->back_alert == 3 || place_out->left_alert == 3 || place_out->right_alert == 3 ) && place_out->Assist_mode == 1 ) ) || ( inputs->btnF_L && !( place_out->front_alert == 1 && place_out->Assist_mode == 1 ) ) ) && !( inputs->btnR || inputs->btnF_R || inputs->btnB_R ) && !( ( inputs->btnF || inputs->btnF_R || inputs->btnF_L ) && ( inputs->btnB || inputs->btnB_R || inputs->btnB_L ) ) );
}

void t_777_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_448--;
}

void t_777_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_386++;
}

void t_777_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 780 - obstacle_control */
int t_780_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_386 >= 1 );
}

int t_780_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_780_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( place_out->back_alert == 3 || place_out->left_alert == 3 || place_out->right_alert == 3 ) && place_out->Assist_mode == 1 && inputs->btnB_L == 1 );
}

void t_780_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_386--;
}

void t_780_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_448++;
}

void t_780_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 783 - obstacle_control_2 */
int t_783_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_386 >= 1 );
}

int t_783_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_783_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->right_alert == 3 && place_out->Assist_mode == 1 && inputs->btnL == 1 );
}

void t_783_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_386--;
}

void t_783_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_448++;
}

void t_783_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 786 - obstacle_control */
int t_786_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_726 >= 1 );
}

int t_786_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_786_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( ( place_out->back_alert == 3 || place_out->left_alert == 3 || place_out->right_alert == 3 ) && place_out->Assist_mode == 1 && inputs->btnB_R == 1 );
}

void t_786_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_726--;
}

void t_786_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_729++;
}

void t_786_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 787 - obstacle_control_2 */
int t_787_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_726 >= 1 );
}

int t_787_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_787_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->right_alert == 3 && place_out->Assist_mode == 1 && inputs->btnR == 1 );
}

void t_787_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_726--;
}

void t_787_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_729++;
}

void t_787_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 824 - up */
int t_824_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_822 >= 1 );
}

int t_824_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_824_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->pitch >= 5 );
}

void t_824_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_822--;
}

void t_824_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_823++;
}

void t_824_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 825 - down */
int t_825_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_823 >= 1 );
}

int t_825_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_825_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->pitch < 5 );
}

void t_825_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_823--;
}

void t_825_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_822++;
}

void t_825_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 836 - up */
int t_836_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_823 >= 1 );
}

int t_836_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_836_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->pitch >= 10 );
}

void t_836_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_823--;
}

void t_836_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_835++;
}

void t_836_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 837 - down */
int t_837_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_835 >= 1 );
}

int t_837_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_837_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->pitch < 10 );
}

void t_837_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_835--;
}

void t_837_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_823++;
}

void t_837_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 843 - up */
int t_843_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_835 >= 1 );
}

int t_843_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_843_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->pitch >= 15 );
}

void t_843_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_835--;
}

void t_843_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_842++;
}

void t_843_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 844 - down */
int t_844_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_842 >= 1 );
}

int t_844_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_844_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->pitch < 15 );
}

void t_844_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_842--;
}

void t_844_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_835++;
}

void t_844_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 850 - down_1 */
int t_850_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_822 >= 1 );
}

int t_850_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_850_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->pitch <= -5 );
}

void t_850_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_822--;
}

void t_850_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_849++;
}

void t_850_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 851 - up_1 */
int t_851_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_849 >= 1 );
}

int t_851_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_851_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->pitch > -5 );
}

void t_851_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_849--;
}

void t_851_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_822++;
}

void t_851_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 853 - down_1 */
int t_853_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_849 >= 1 );
}

int t_853_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_853_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->pitch <= -10 );
}

void t_853_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_849--;
}

void t_853_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_852++;
}

void t_853_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 854 - up_1 */
int t_854_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_852 >= 1 );
}

int t_854_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_854_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->pitch > -10 );
}

void t_854_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_852--;
}

void t_854_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_849++;
}

void t_854_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 856 - down_1 */
int t_856_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_852 >= 1 );
}

int t_856_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_856_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->pitch <= -15 );
}

void t_856_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_852--;
}

void t_856_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_855++;
}

void t_856_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 857 - up_1 */
int t_857_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_855 >= 1 );
}

int t_857_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_857_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->pitch > -15 );
}

void t_857_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_855--;
}

void t_857_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_852++;
}

void t_857_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 870 - increase_assist_1 */
int t_870_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_502 >= 1 );
}

int t_870_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_870_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->tpi_inChg == 1 && place_out->Assist_mode == 1 && ( ( place_out->pitch_alert == 1 && place_out->ForwardQ == 0 ) || ( place_out->pitch_alert == -1 && place_out->ReverseQ == 0 ) ) );
}

void t_870_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_502--;
}

void t_870_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_503++;
}

void t_870_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 873 - increase_assist_2 */
int t_873_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_503 >= 1 );
}

int t_873_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_873_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->tpi_inChg == 1 && place_out->Assist_mode == 1 && ( ( place_out->pitch_alert == 2 && place_out->ForwardQ == 0 ) || ( place_out->pitch_alert == -2 && place_out->ReverseQ == 0 ) ) );
}

void t_873_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_503--;
}

void t_873_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_504++;
}

void t_873_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 876 - increase_assist_3 */
int t_876_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_504 >= 1 );
}

int t_876_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_876_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->tpi_inChg == 1 && place_out->Assist_mode == 1 && ( ( place_out->pitch_alert == 3 && place_out->ForwardQ == 0 ) || ( place_out->pitch_alert == -3 && place_out->ReverseQ == 0 ) ) );
}

void t_876_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_504--;
}

void t_876_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_505++;
}

void t_876_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 879 - decrease_assist_3 */
int t_879_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_503 >= 1 );
}

int t_879_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_879_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->tpi_inChg == 1 && place_out->Assist_mode == 1 && ( ( place_out->pitch_alert == -3 && place_out->ForwardQ == 0 ) || ( place_out->pitch_alert == 3 && place_out->ReverseQ == 0 ) ) );
}

void t_879_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_503--;
}

void t_879_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_502++;
}

void t_879_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 880 - decrease_assist_2 */
int t_880_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_504 >= 1 );
}

int t_880_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_880_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->tpi_inChg == 1 && place_out->Assist_mode == 1 && ( ( place_out->pitch_alert == -2 && place_out->ForwardQ == 0 ) || ( place_out->pitch_alert == 2 && place_out->ReverseQ == 0 ) ) );
}

void t_880_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_504--;
}

void t_880_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_503++;
}

void t_880_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 881 - decrease_assist_1 */
int t_881_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_505 >= 1 );
}

int t_881_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_881_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->tpi_inChg == 1 && place_out->Assist_mode == 1 && ( ( place_out->pitch_alert == -1 && place_out->ForwardQ == 0 ) || ( place_out->pitch_alert == 1 && place_out->ReverseQ == 0 ) ) );
}

void t_881_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_505--;
}

void t_881_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_504++;
}

void t_881_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 888 - horn_ON_step */
int t_888_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_496 >= 1 );
}

int t_888_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_888_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->tpi_inChg == 1 && place_out->front_alert == 1 && place_out->ForwardQ == 0 );
}

void t_888_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_496--;
}

void t_888_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_495++;
}

void t_888_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 895 - horn_OFF_joyInChg */
int t_895_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_495 >= 1 );
}

int t_895_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_895_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( inputs->inChg != 0 );
}

void t_895_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_495--;
}

void t_895_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_496++;
}

void t_895_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Transition 901 - horn_ON_obstacle */
int t_901_enabled( ACM_signals_NetMarking* prev,
                    ACM_signals_NetMarking* avail )
{
    return ( avail->p_496 >= 1 );
}

int t_901_events( ACM_signals_InputSignalEvents* events )
{
    return (  1  );
}

int t_901_guards( ACM_signals_NetMarking* marking,
                   ACM_signals_InputSignals* inputs,
                   ACM_signals_PlaceOutputSignals* place_out,
                   ACM_signals_EventOutputSignals* ev_out )
{
    return ( place_out->tpi_inChg == 1 && ( place_out->back_alert == 3 || place_out->left_alert == 3 || place_out->right_alert == 3 ) && place_out->ReverseQ == 0 );
}

void t_901_remove_marks( ACM_signals_NetMarking* marking )
{
    marking->p_496--;
}

void t_901_add_marks( ACM_signals_NetMarking* marking )
{
    marking->p_495++;
}

void t_901_generate_output_events( ACM_signals_OutputSignalEvents* ev_out )
{
}


/* Input event processing: */
void ACM_signals_GenerateInputSignalEvents(
        ACM_signals_InputSignals *old_values,
        ACM_signals_InputSignals *new_values,
        ACM_signals_InputSignalEvents *events )
{
    events->btnInc_up = ( old_values->btnInc<=0 && new_values->btnInc>0 );
    events->btnDec_up = ( old_values->btnDec<=0 && new_values->btnDec>0 );
    events->btnAssist_mode_up = ( old_values->btnAssist_mode<=0 && new_values->btnAssist_mode>0 );
}

/* Output event processing: */
void ACM_signals_GenerateEventOutputSignals(
    ACM_signals_OutputSignalEvents *events,
    ACM_signals_EventOutputSignals *signals )
{
}

/* Transition action processing: */
void ACM_signals_GenerateTransitionActionOutputSignals(
    ACM_signals_TransitionFiring *tfired,
    ACM_signals_NetMarking *marking,
    ACM_signals_EventOutputSignals *ev_out )
{
}

/* Place Output Processing */
void ACM_signals_GeneratePlaceOutputSignals(
    ACM_signals_NetMarking *marking,
    ACM_signals_InputSignals *inputs,
    ACM_signals_PlaceOutputSignals *place_out,
    ACM_signals_EventOutputSignals *ev_out )
{
    int exp_res, new_val, n_writes;
    ACM_signals_PlaceOutputSignals new_out = *place_out;
    
    /* Signal tpi_inChg */
    new_val = 0;
    if( marking->p_308 > 0 ) { /* Place joy_inChg */
        exp_res = 0;
        if( 1 )
            new_val = exp_res;
    }
    if( marking->p_306 > 0 ) { /* Place tpi_inChg */
        exp_res = 1;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.tpi_inChg = 1;
    else if( new_val < 0 ) new_out.tpi_inChg = 0;
    else new_out.tpi_inChg = new_val;

    /* Signal ForwardQ */
    new_val = 1;
    if( marking->p_710 > 0 ) { /* Place Forward */
        exp_res = 0;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.ForwardQ = 1;
    else if( new_val < 0 ) new_out.ForwardQ = 0;
    else new_out.ForwardQ = new_val;

    /* Signal ReverseQ */
    new_val = 1;
    if( marking->p_387 > 0 ) { /* Place Backward */
        exp_res = 0;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.ReverseQ = 1;
    else if( new_val < 0 ) new_out.ReverseQ = 0;
    else new_out.ReverseQ = new_val;

    /* Signal RightQ */
    new_val = 1;
    if( marking->p_726 > 0 ) { /* Place Right */
        exp_res = 0;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.RightQ = 1;
    else if( new_val < 0 ) new_out.RightQ = 0;
    else new_out.RightQ = new_val;

    /* Signal LeftQ */
    new_val = 1;
    if( marking->p_386 > 0 ) { /* Place Left */
        exp_res = 0;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.LeftQ = 1;
    else if( new_val < 0 ) new_out.LeftQ = 0;
    else new_out.LeftQ = new_val;

    /* Signal Horn */
    new_val = 0;
    if( marking->p_496 > 0 ) { /* Place horn_OFF */
        exp_res = 0;
        if( 1 )
            new_val = exp_res;
    }
    if( marking->p_495 > 0 ) { /* Place horn_ON_button */
        exp_res = 1;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Horn = 1;
    else if( new_val < 0 ) new_out.Horn = 0;
    else new_out.Horn = new_val;

    /* Signal speedDial */
    new_val = 0;
    if( marking->p_505 > 0 ) { /* Place speed_100 */
        exp_res = 3;
        if( 1 )
            new_val = exp_res;
    }
    if( marking->p_502 > 0 ) { /* Place speed_25 */
        exp_res = 0;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( marking->p_503 > 0 ) { /* Place speed_50 */
        exp_res = 1;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( marking->p_504 > 0 ) { /* Place speed_75 */
        exp_res = 2;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( new_val > 3 ) new_out.speedDial = 3;
    else if( new_val < 0 ) new_out.speedDial = 0;
    else new_out.speedDial = new_val;

    /* Signal back_alert */
    new_val = 0;
    if( marking->p_545 > 0 ) { /* Place back_0 */
        exp_res = 0;
        if( 1 )
            new_val = exp_res;
    }
    if( marking->p_546 > 0 ) { /* Place back_1 */
        exp_res = 1;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( marking->p_547 > 0 ) { /* Place back_2 */
        exp_res = 2;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( marking->p_548 > 0 ) { /* Place back_3 */
        exp_res = 3;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( new_val > 3 ) new_out.back_alert = 3;
    else if( new_val < 0 ) new_out.back_alert = 0;
    else new_out.back_alert = new_val;

    /* Signal left_alert */
    new_val = 0;
    if( marking->p_567 > 0 ) { /* Place left_0 */
        exp_res = 0;
        if( 1 )
            new_val = exp_res;
    }
    if( marking->p_568 > 0 ) { /* Place left_1 */
        exp_res = 1;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( marking->p_569 > 0 ) { /* Place left_2 */
        exp_res = 2;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( marking->p_570 > 0 ) { /* Place left_3 */
        exp_res = 3;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( new_val > 3 ) new_out.left_alert = 3;
    else if( new_val < 0 ) new_out.left_alert = 0;
    else new_out.left_alert = new_val;

    /* Signal right_alert */
    new_val = 0;
    if( marking->p_589 > 0 ) { /* Place right_0 */
        exp_res = 0;
        if( 1 )
            new_val = exp_res;
    }
    if( marking->p_590 > 0 ) { /* Place right_1 */
        exp_res = 1;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( marking->p_591 > 0 ) { /* Place right_2 */
        exp_res = 2;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( marking->p_592 > 0 ) { /* Place right_3 */
        exp_res = 3;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( new_val > 3 ) new_out.right_alert = 3;
    else if( new_val < 0 ) new_out.right_alert = 0;
    else new_out.right_alert = new_val;

    /* Signal front_alert */
    new_val = 0;
    if( marking->p_611 > 0 ) { /* Place front_flat */
        exp_res = 0;
        if( 1 )
            new_val = exp_res;
    }
    if( marking->p_612 > 0 ) { /* Place front_step */
        exp_res = 1;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.front_alert = 1;
    else if( new_val < 0 ) new_out.front_alert = 0;
    else new_out.front_alert = new_val;

    /* Signal Assist_mode */
    new_val = 0;
    if( marking->p_635 > 0 ) { /* Place Assist_mode_OFF */
        exp_res = 0;
        if( 1 )
            new_val = exp_res;
    }
    if( marking->p_634 > 0 ) { /* Place Assist_mode_ON */
        exp_res = 1;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Assist_mode = 1;
    else if( new_val < 0 ) new_out.Assist_mode = 0;
    else new_out.Assist_mode = new_val;

    /* Signal pitch_alert */
    new_val = 0;
    if( marking->p_822 > 0 ) { /* Place leveled */
        exp_res = 0;
        if( 1 )
            new_val = exp_res;
    }
    if( marking->p_849 > 0 ) { /* Place tilted_down_1 */
        exp_res = -1;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( marking->p_852 > 0 ) { /* Place tilted_down_2 */
        exp_res = -2;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( marking->p_855 > 0 ) { /* Place tilted_down_3 */
        exp_res = -3;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( marking->p_823 > 0 ) { /* Place tilted_up_1 */
        exp_res = 1;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( marking->p_835 > 0 ) { /* Place tilted_up_2 */
        exp_res = 2;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( marking->p_842 > 0 ) { /* Place tilted_up_3 */
        exp_res = 3;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( new_val > 3 ) new_out.pitch_alert = 3;
    else if( new_val < -3 ) new_out.pitch_alert = -3;
    else new_out.pitch_alert = new_val;

    *place_out = new_out;
}

