/* Net ACM_signals - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <stdlib.h>
#include "net_types.h"


int trace_control = TRACE_CONT_RUN;

extern void httpServer_init();
extern void httpServer_getRequest();
extern void httpServer_sendResponse();
extern void httpServer_disconnectClient();
extern void httpServer_checkBreakPoints();
extern void httpServer_finish();

static ACM_signals_NetMarking marking;
static ACM_signals_InputSignals inputs, prev_inputs;
static ACM_signals_PlaceOutputSignals place_out;
static ACM_signals_EventOutputSignals ev_out;

void setup()
{
    createInitial_ACM_signals_NetMarking( &marking );
    init_ACM_signals_OutputSignals( &place_out, &ev_out );
    ACM_signals_InitializeIO();
    ACM_signals_GetInputSignals( &prev_inputs, NULL );
#ifdef HTTP_SERVER
    httpServer_init();
#endif
}

void loop()
{
#ifdef HTTP_SERVER
    httpServer_getRequest();
#endif

    if( trace_control != TRACE_PAUSE )
        ACM_signals_ExecutionStep( &marking, &inputs, &prev_inputs, &place_out, &ev_out );
    else ACM_signals_GetInputSignals( &inputs, NULL );
    if( trace_control > TRACE_PAUSE ) --trace_control;

#ifdef HTTP_SERVER
    httpServer_sendResponse();
#endif

    ACM_signals_LoopDelay();

#ifdef HTTP_SERVER
    httpServer_disconnectClient();
    httpServer_checkBreakPoints();
#endif
}

#ifndef ARDUINO
int main()
{
    setup();

    do loop();
    while( ACM_signals_FinishExecution( &marking ) == 0 );

#ifdef HTTP_SERVER
    httpServer_finish();
#endif

    return 0;
}
#endif


ACM_signals_NetMarking* get_ACM_signals_NetMarking()
{
    return &marking;
}

ACM_signals_InputSignals* get_ACM_signals_InputSignals()
{
    return &inputs;
}

ACM_signals_PlaceOutputSignals* get_ACM_signals_PlaceOutputSignals()
{
    return &place_out;
}

ACM_signals_EventOutputSignals* get_ACM_signals_EventOutputSignals()
{
    return &ev_out;
}

