/* Net ACM_signals - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */
/* Please fill the necessary code to perform hardware IO. */


#include <stdlib.h>
#include "net_types.h"


#ifdef ARDUINO
#include <Arduino.h>
#define ANALOG_IN_MAX  1023
#define ANALOG_OUT_MAX 255
#else
#define INPUT    0
#define OUTPUT   1
#define ANALOG_IN_MAX  1023
#define ANALOG_OUT_MAX 1023
extern void pinMode( int, int );
extern int  digitalRead( int );
extern void digitalWrite( int, int );
extern int  analogRead( int );
extern void analogWrite( int, int );
#endif


// Remote IcE/Debug forced values:
#ifdef HTTP_SERVER
iopt_param_info *input_fv = NULL, *output_fv = NULL;
#endif


/* Executed just once, before net execution starts: */
void ACM_signals_InitializeIO()
{
    pinMode( 21, INPUT ); /* inChg */
    pinMode( 0, INPUT ); /* btnF_R */
    pinMode( 0, INPUT ); /* btnF */
    pinMode( 0, INPUT ); /* btnF_L */
    pinMode( 0, INPUT ); /* btnL */
    pinMode( 0, INPUT ); /* btnR */
    pinMode( 0, INPUT ); /* btnB */
    pinMode( 0, INPUT ); /* btnB_R */
    pinMode( 0, INPUT ); /* btnB_L */
    pinMode( 0, INPUT ); /* btnHorn */
    pinMode( 0, INPUT ); /* btnInc */
    pinMode( 0, INPUT ); /* btnDec */
    pinMode( 0, INPUT ); /* front_sensor_dist */
    pinMode( 0, INPUT ); /* back_sensor_dist */
    pinMode( 0, INPUT ); /* left_sensor_dist */
    pinMode( 0, INPUT ); /* right_sensor_dist */
    pinMode( 0, INPUT ); /* dist_min */
    pinMode( 0, INPUT ); /* btnAssist_mode */
    pinMode( 0, INPUT ); /* pitch */
    pinMode( 0, OUTPUT ); /* tpi_inChg */
    pinMode( 5, OUTPUT ); /* ForwardQ */
    pinMode( 6, OUTPUT ); /* ReverseQ */
    pinMode( 13, OUTPUT ); /* RightQ */
    pinMode( 19, OUTPUT ); /* LeftQ */
    pinMode( 26, OUTPUT ); /* Horn */
    pinMode( 0, OUTPUT ); /* speedDial */
    pinMode( 0, OUTPUT ); /* back_alert */
    pinMode( 0, OUTPUT ); /* left_alert */
    pinMode( 0, OUTPUT ); /* right_alert */
    pinMode( 0, OUTPUT ); /* front_alert */
    pinMode( 0, OUTPUT ); /* Assist_mode */
    pinMode( 0, OUTPUT ); /* pitch_alert */
}



/* Read all hardware input signals and fill data-structure */
void ACM_signals_GetInputSignals(
            ACM_signals_InputSignals* inputs,
            ACM_signals_InputSignalEvents* events )
{
    inputs->inChg = digitalRead( 21 );
    inputs->btnF_R = digitalRead( 0 );
    inputs->btnF = digitalRead( 0 );
    inputs->btnF_L = digitalRead( 0 );
    inputs->btnL = digitalRead( 0 );
    inputs->btnR = digitalRead( 0 );
    inputs->btnB = digitalRead( 0 );
    inputs->btnB_R = digitalRead( 0 );
    inputs->btnB_L = digitalRead( 0 );
    inputs->btnHorn = digitalRead( 0 );
    inputs->btnInc = digitalRead( 0 );
    inputs->btnDec = digitalRead( 0 );
    inputs->front_sensor_dist = analogRead( 0 ) * (100 - 0) / ANALOG_IN_MAX + 0;
    inputs->back_sensor_dist = analogRead( 0 ) * (200 - 0) / ANALOG_IN_MAX + 0;
    inputs->left_sensor_dist = analogRead( 0 ) * (200 - 0) / ANALOG_IN_MAX + 0;
    inputs->right_sensor_dist = analogRead( 0 ) * (200 - 0) / ANALOG_IN_MAX + 0;
    inputs->dist_min = analogRead( 0 ) * (50 - 30) / ANALOG_IN_MAX + 30;
    inputs->btnAssist_mode = digitalRead( 0 );
    inputs->pitch = analogRead( 0 ) * (20 - -20) / ANALOG_IN_MAX + -20;
#ifdef HTTP_SERVER
    if( input_fv != NULL ) force_ACM_signals_Inputs( input_fv, inputs );
#endif
}


/* Write all output values to physical hardware outputs */
void ACM_signals_PutOutputSignals(
            ACM_signals_PlaceOutputSignals* place_out,
            ACM_signals_EventOutputSignals* event_out,
            ACM_signals_OutputSignalEvents* events )
{
#ifdef HTTP_SERVER
    if( output_fv != NULL )
        force_ACM_signals_Outputs( output_fv, place_out, event_out );
#endif
    digitalWrite( 0, place_out->tpi_inChg );
    digitalWrite( 5, place_out->ForwardQ );
    digitalWrite( 6, place_out->ReverseQ );
    digitalWrite( 13, place_out->RightQ );
    digitalWrite( 19, place_out->LeftQ );
    digitalWrite( 26, place_out->Horn );
    analogWrite( 0, (place_out->speedDial - 0) * ANALOG_OUT_MAX / (3 - 0) );
    analogWrite( 0, (place_out->back_alert - 0) * ANALOG_OUT_MAX / (3 - 0) );
    analogWrite( 0, (place_out->left_alert - 0) * ANALOG_OUT_MAX / (3 - 0) );
    analogWrite( 0, (place_out->right_alert - 0) * ANALOG_OUT_MAX / (3 - 0) );
    digitalWrite( 0, place_out->front_alert );
    digitalWrite( 0, place_out->Assist_mode );
    analogWrite( 0, (place_out->pitch_alert - -3) * ANALOG_OUT_MAX / (3 - -3) );
}


/* Delay between loop iterations to save CPU and power consumption */
void ACM_signals_LoopDelay()
{
}

/* Must return 1 to finish net execution */
int ACM_signals_FinishExecution( ACM_signals_NetMarking* marking )
{
    return 0;
}



