/* Net ACM_signals - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <stdlib.h>
#include <string.h>
#include "net_types.h"


static ACM_signals_TransitionFiring tfired;
    

void ACM_signals_ExecutionStep(
     ACM_signals_NetMarking *prev_marking,
     ACM_signals_InputSignals *inputs,
     ACM_signals_InputSignals *prev_in,
     ACM_signals_PlaceOutputSignals *place_out,
     ACM_signals_EventOutputSignals *ev_out )
{
    ACM_signals_NetMarking add_marking;
    ACM_signals_NetMarking avail_marking = *prev_marking;
    ACM_signals_InputSignalEvents input_events;
    ACM_signals_OutputSignalEvents output_events;

    memset( &output_events, 0, sizeof(output_events) );
    memset( &tfired, 0, sizeof(tfired) );

    createEmpty_ACM_signals_NetMarking( &add_marking );
    ACM_signals_GetInputSignals( inputs, &input_events );
    ACM_signals_GenerateInputSignalEvents( prev_in, inputs, &input_events );
    *prev_in = *inputs;

    /* Transition change_Joy */
    if( t_305_enabled( prev_marking, &avail_marking ) &&
        t_305_events( &input_events ) &&
        t_305_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_305 = 1;
        t_305_remove_marks( &avail_marking );
        t_305_add_marks( &add_marking );
        t_305_generate_output_events( &output_events );
    }

    /* Transition change_TPI */
    if( t_322_enabled( prev_marking, &avail_marking ) &&
        t_322_events( &input_events ) &&
        t_322_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_322 = 1;
        t_322_remove_marks( &avail_marking );
        t_322_add_marks( &add_marking );
        t_322_generate_output_events( &output_events );
    }

    /* Transition stop_RightON */
    if( t_398_enabled( prev_marking, &avail_marking ) &&
        t_398_events( &input_events ) &&
        t_398_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_398 = 1;
        t_398_remove_marks( &avail_marking );
        t_398_add_marks( &add_marking );
        t_398_generate_output_events( &output_events );
    }

    /* Transition stop_FrontON */
    if( t_473_enabled( prev_marking, &avail_marking ) &&
        t_473_events( &input_events ) &&
        t_473_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_473 = 1;
        t_473_remove_marks( &avail_marking );
        t_473_add_marks( &add_marking );
        t_473_generate_output_events( &output_events );
    }

    /* Transition stop_LeftOFF */
    if( t_482_enabled( prev_marking, &avail_marking ) &&
        t_482_events( &input_events ) &&
        t_482_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_482 = 1;
        t_482_remove_marks( &avail_marking );
        t_482_add_marks( &add_marking );
        t_482_generate_output_events( &output_events );
    }

    /* Transition stop_BackOFF */
    if( t_485_enabled( prev_marking, &avail_marking ) &&
        t_485_events( &input_events ) &&
        t_485_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_485 = 1;
        t_485_remove_marks( &avail_marking );
        t_485_add_marks( &add_marking );
        t_485_generate_output_events( &output_events );
    }

    /* Transition horn_OFF */
    if( t_494_enabled( prev_marking, &avail_marking ) &&
        t_494_events( &input_events ) &&
        t_494_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_494 = 1;
        t_494_remove_marks( &avail_marking );
        t_494_add_marks( &add_marking );
        t_494_generate_output_events( &output_events );
    }

    /* Transition horn_ON */
    if( t_497_enabled( prev_marking, &avail_marking ) &&
        t_497_events( &input_events ) &&
        t_497_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_497 = 1;
        t_497_remove_marks( &avail_marking );
        t_497_add_marks( &add_marking );
        t_497_generate_output_events( &output_events );
    }

    /* Transition increase */
    if( t_506_enabled( prev_marking, &avail_marking ) &&
        t_506_events( &input_events ) &&
        t_506_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_506 = 1;
        t_506_remove_marks( &avail_marking );
        t_506_add_marks( &add_marking );
        t_506_generate_output_events( &output_events );
    }

    /* Transition decrease */
    if( t_507_enabled( prev_marking, &avail_marking ) &&
        t_507_events( &input_events ) &&
        t_507_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_507 = 1;
        t_507_remove_marks( &avail_marking );
        t_507_add_marks( &add_marking );
        t_507_generate_output_events( &output_events );
    }

    /* Transition decrease_2 */
    if( t_508_enabled( prev_marking, &avail_marking ) &&
        t_508_events( &input_events ) &&
        t_508_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_508 = 1;
        t_508_remove_marks( &avail_marking );
        t_508_add_marks( &add_marking );
        t_508_generate_output_events( &output_events );
    }

    /* Transition increase_2 */
    if( t_509_enabled( prev_marking, &avail_marking ) &&
        t_509_events( &input_events ) &&
        t_509_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_509 = 1;
        t_509_remove_marks( &avail_marking );
        t_509_add_marks( &add_marking );
        t_509_generate_output_events( &output_events );
    }

    /* Transition decrease_3 */
    if( t_510_enabled( prev_marking, &avail_marking ) &&
        t_510_events( &input_events ) &&
        t_510_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_510 = 1;
        t_510_remove_marks( &avail_marking );
        t_510_add_marks( &add_marking );
        t_510_generate_output_events( &output_events );
    }

    /* Transition increase_3 */
    if( t_511_enabled( prev_marking, &avail_marking ) &&
        t_511_events( &input_events ) &&
        t_511_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_511 = 1;
        t_511_remove_marks( &avail_marking );
        t_511_add_marks( &add_marking );
        t_511_generate_output_events( &output_events );
    }

    /* Transition closer */
    if( t_549_enabled( prev_marking, &avail_marking ) &&
        t_549_events( &input_events ) &&
        t_549_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_549 = 1;
        t_549_remove_marks( &avail_marking );
        t_549_add_marks( &add_marking );
        t_549_generate_output_events( &output_events );
    }

    /* Transition further */
    if( t_550_enabled( prev_marking, &avail_marking ) &&
        t_550_events( &input_events ) &&
        t_550_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_550 = 1;
        t_550_remove_marks( &avail_marking );
        t_550_add_marks( &add_marking );
        t_550_generate_output_events( &output_events );
    }

    /* Transition further */
    if( t_551_enabled( prev_marking, &avail_marking ) &&
        t_551_events( &input_events ) &&
        t_551_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_551 = 1;
        t_551_remove_marks( &avail_marking );
        t_551_add_marks( &add_marking );
        t_551_generate_output_events( &output_events );
    }

    /* Transition closer */
    if( t_552_enabled( prev_marking, &avail_marking ) &&
        t_552_events( &input_events ) &&
        t_552_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_552 = 1;
        t_552_remove_marks( &avail_marking );
        t_552_add_marks( &add_marking );
        t_552_generate_output_events( &output_events );
    }

    /* Transition further */
    if( t_553_enabled( prev_marking, &avail_marking ) &&
        t_553_events( &input_events ) &&
        t_553_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_553 = 1;
        t_553_remove_marks( &avail_marking );
        t_553_add_marks( &add_marking );
        t_553_generate_output_events( &output_events );
    }

    /* Transition closer */
    if( t_554_enabled( prev_marking, &avail_marking ) &&
        t_554_events( &input_events ) &&
        t_554_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_554 = 1;
        t_554_remove_marks( &avail_marking );
        t_554_add_marks( &add_marking );
        t_554_generate_output_events( &output_events );
    }

    /* Transition closer_2 */
    if( t_571_enabled( prev_marking, &avail_marking ) &&
        t_571_events( &input_events ) &&
        t_571_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_571 = 1;
        t_571_remove_marks( &avail_marking );
        t_571_add_marks( &add_marking );
        t_571_generate_output_events( &output_events );
    }

    /* Transition further_2 */
    if( t_572_enabled( prev_marking, &avail_marking ) &&
        t_572_events( &input_events ) &&
        t_572_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_572 = 1;
        t_572_remove_marks( &avail_marking );
        t_572_add_marks( &add_marking );
        t_572_generate_output_events( &output_events );
    }

    /* Transition further_3 */
    if( t_573_enabled( prev_marking, &avail_marking ) &&
        t_573_events( &input_events ) &&
        t_573_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_573 = 1;
        t_573_remove_marks( &avail_marking );
        t_573_add_marks( &add_marking );
        t_573_generate_output_events( &output_events );
    }

    /* Transition closer_3 */
    if( t_574_enabled( prev_marking, &avail_marking ) &&
        t_574_events( &input_events ) &&
        t_574_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_574 = 1;
        t_574_remove_marks( &avail_marking );
        t_574_add_marks( &add_marking );
        t_574_generate_output_events( &output_events );
    }

    /* Transition further_4 */
    if( t_575_enabled( prev_marking, &avail_marking ) &&
        t_575_events( &input_events ) &&
        t_575_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_575 = 1;
        t_575_remove_marks( &avail_marking );
        t_575_add_marks( &add_marking );
        t_575_generate_output_events( &output_events );
    }

    /* Transition closer_4 */
    if( t_576_enabled( prev_marking, &avail_marking ) &&
        t_576_events( &input_events ) &&
        t_576_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_576 = 1;
        t_576_remove_marks( &avail_marking );
        t_576_add_marks( &add_marking );
        t_576_generate_output_events( &output_events );
    }

    /* Transition closer_5 */
    if( t_593_enabled( prev_marking, &avail_marking ) &&
        t_593_events( &input_events ) &&
        t_593_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_593 = 1;
        t_593_remove_marks( &avail_marking );
        t_593_add_marks( &add_marking );
        t_593_generate_output_events( &output_events );
    }

    /* Transition further_5 */
    if( t_594_enabled( prev_marking, &avail_marking ) &&
        t_594_events( &input_events ) &&
        t_594_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_594 = 1;
        t_594_remove_marks( &avail_marking );
        t_594_add_marks( &add_marking );
        t_594_generate_output_events( &output_events );
    }

    /* Transition further_6 */
    if( t_595_enabled( prev_marking, &avail_marking ) &&
        t_595_events( &input_events ) &&
        t_595_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_595 = 1;
        t_595_remove_marks( &avail_marking );
        t_595_add_marks( &add_marking );
        t_595_generate_output_events( &output_events );
    }

    /* Transition closer_6 */
    if( t_596_enabled( prev_marking, &avail_marking ) &&
        t_596_events( &input_events ) &&
        t_596_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_596 = 1;
        t_596_remove_marks( &avail_marking );
        t_596_add_marks( &add_marking );
        t_596_generate_output_events( &output_events );
    }

    /* Transition further_7 */
    if( t_597_enabled( prev_marking, &avail_marking ) &&
        t_597_events( &input_events ) &&
        t_597_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_597 = 1;
        t_597_remove_marks( &avail_marking );
        t_597_add_marks( &add_marking );
        t_597_generate_output_events( &output_events );
    }

    /* Transition closer_7 */
    if( t_598_enabled( prev_marking, &avail_marking ) &&
        t_598_events( &input_events ) &&
        t_598_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_598 = 1;
        t_598_remove_marks( &avail_marking );
        t_598_add_marks( &add_marking );
        t_598_generate_output_events( &output_events );
    }

    /* Transition step_detect */
    if( t_615_enabled( prev_marking, &avail_marking ) &&
        t_615_events( &input_events ) &&
        t_615_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_615 = 1;
        t_615_remove_marks( &avail_marking );
        t_615_add_marks( &add_marking );
        t_615_generate_output_events( &output_events );
    }

    /* Transition no_step */
    if( t_616_enabled( prev_marking, &avail_marking ) &&
        t_616_events( &input_events ) &&
        t_616_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_616 = 1;
        t_616_remove_marks( &avail_marking );
        t_616_add_marks( &add_marking );
        t_616_generate_output_events( &output_events );
    }

    /* Transition change_ON */
    if( t_643_enabled( prev_marking, &avail_marking ) &&
        t_643_events( &input_events ) &&
        t_643_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_643 = 1;
        t_643_remove_marks( &avail_marking );
        t_643_add_marks( &add_marking );
        t_643_generate_output_events( &output_events );
    }

    /* Transition change_joyInChg */
    if( t_651_enabled( prev_marking, &avail_marking ) &&
        t_651_events( &input_events ) &&
        t_651_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_651 = 1;
        t_651_remove_marks( &avail_marking );
        t_651_add_marks( &add_marking );
        t_651_generate_output_events( &output_events );
    }

    /* Transition change_OFF */
    if( t_652_enabled( prev_marking, &avail_marking ) &&
        t_652_events( &input_events ) &&
        t_652_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_652 = 1;
        t_652_remove_marks( &avail_marking );
        t_652_add_marks( &add_marking );
        t_652_generate_output_events( &output_events );
    }

    /* Transition step_control */
    if( t_673_enabled( prev_marking, &avail_marking ) &&
        t_673_events( &input_events ) &&
        t_673_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_673 = 1;
        t_673_remove_marks( &avail_marking );
        t_673_add_marks( &add_marking );
        t_673_generate_output_events( &output_events );
    }

    /* Transition stop_joyInChg */
    if( t_685_enabled( prev_marking, &avail_marking ) &&
        t_685_events( &input_events ) &&
        t_685_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_685 = 1;
        t_685_remove_marks( &avail_marking );
        t_685_add_marks( &add_marking );
        t_685_generate_output_events( &output_events );
    }

    /* Transition stop_joyInChg */
    if( t_686_enabled( prev_marking, &avail_marking ) &&
        t_686_events( &input_events ) &&
        t_686_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_686 = 1;
        t_686_remove_marks( &avail_marking );
        t_686_add_marks( &add_marking );
        t_686_generate_output_events( &output_events );
    }

    /* Transition obstacle_control */
    if( t_694_enabled( prev_marking, &avail_marking ) &&
        t_694_events( &input_events ) &&
        t_694_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_694 = 1;
        t_694_remove_marks( &avail_marking );
        t_694_add_marks( &add_marking );
        t_694_generate_output_events( &output_events );
    }

    /* Transition move_B */
    if( t_707_enabled( prev_marking, &avail_marking ) &&
        t_707_events( &input_events ) &&
        t_707_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_707 = 1;
        t_707_remove_marks( &avail_marking );
        t_707_add_marks( &add_marking );
        t_707_generate_output_events( &output_events );
    }

    /* Transition stop_BackON */
    if( t_711_enabled( prev_marking, &avail_marking ) &&
        t_711_events( &input_events ) &&
        t_711_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_711 = 1;
        t_711_remove_marks( &avail_marking );
        t_711_add_marks( &add_marking );
        t_711_generate_output_events( &output_events );
    }

    /* Transition stop_FrontOFF */
    if( t_712_enabled( prev_marking, &avail_marking ) &&
        t_712_events( &input_events ) &&
        t_712_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_712 = 1;
        t_712_remove_marks( &avail_marking );
        t_712_add_marks( &add_marking );
        t_712_generate_output_events( &output_events );
    }

    /* Transition stop_joyInChg */
    if( t_713_enabled( prev_marking, &avail_marking ) &&
        t_713_events( &input_events ) &&
        t_713_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_713 = 1;
        t_713_remove_marks( &avail_marking );
        t_713_add_marks( &add_marking );
        t_713_generate_output_events( &output_events );
    }

    /* Transition stop_LeftON */
    if( t_728_enabled( prev_marking, &avail_marking ) &&
        t_728_events( &input_events ) &&
        t_728_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_728 = 1;
        t_728_remove_marks( &avail_marking );
        t_728_add_marks( &add_marking );
        t_728_generate_output_events( &output_events );
    }

    /* Transition stop_RightOFF */
    if( t_730_enabled( prev_marking, &avail_marking ) &&
        t_730_events( &input_events ) &&
        t_730_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_730 = 1;
        t_730_remove_marks( &avail_marking );
        t_730_add_marks( &add_marking );
        t_730_generate_output_events( &output_events );
    }

    /* Transition stop_joyInChg */
    if( t_731_enabled( prev_marking, &avail_marking ) &&
        t_731_events( &input_events ) &&
        t_731_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_731 = 1;
        t_731_remove_marks( &avail_marking );
        t_731_add_marks( &add_marking );
        t_731_generate_output_events( &output_events );
    }

    /* Transition move_R */
    if( t_742_enabled( prev_marking, &avail_marking ) &&
        t_742_events( &input_events ) &&
        t_742_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_742 = 1;
        t_742_remove_marks( &avail_marking );
        t_742_add_marks( &add_marking );
        t_742_generate_output_events( &output_events );
    }

    /* Transition stop_FrontBackON */
    if( t_745_enabled( prev_marking, &avail_marking ) &&
        t_745_events( &input_events ) &&
        t_745_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_745 = 1;
        t_745_remove_marks( &avail_marking );
        t_745_add_marks( &add_marking );
        t_745_generate_output_events( &output_events );
    }

    /* Transition stop_FrontBackON */
    if( t_746_enabled( prev_marking, &avail_marking ) &&
        t_746_events( &input_events ) &&
        t_746_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_746 = 1;
        t_746_remove_marks( &avail_marking );
        t_746_add_marks( &add_marking );
        t_746_generate_output_events( &output_events );
    }

    /* Transition stop_LeftRightON */
    if( t_752_enabled( prev_marking, &avail_marking ) &&
        t_752_events( &input_events ) &&
        t_752_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_752 = 1;
        t_752_remove_marks( &avail_marking );
        t_752_add_marks( &add_marking );
        t_752_generate_output_events( &output_events );
    }

    /* Transition stop_LeftRightON */
    if( t_757_enabled( prev_marking, &avail_marking ) &&
        t_757_events( &input_events ) &&
        t_757_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_757 = 1;
        t_757_remove_marks( &avail_marking );
        t_757_add_marks( &add_marking );
        t_757_generate_output_events( &output_events );
    }

    /* Transition step_control */
    if( t_765_enabled( prev_marking, &avail_marking ) &&
        t_765_events( &input_events ) &&
        t_765_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_765 = 1;
        t_765_remove_marks( &avail_marking );
        t_765_add_marks( &add_marking );
        t_765_generate_output_events( &output_events );
    }

    /* Transition step_control */
    if( t_768_enabled( prev_marking, &avail_marking ) &&
        t_768_events( &input_events ) &&
        t_768_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_768 = 1;
        t_768_remove_marks( &avail_marking );
        t_768_add_marks( &add_marking );
        t_768_generate_output_events( &output_events );
    }

    /* Transition move_F */
    if( t_771_enabled( prev_marking, &avail_marking ) &&
        t_771_events( &input_events ) &&
        t_771_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_771 = 1;
        t_771_remove_marks( &avail_marking );
        t_771_add_marks( &add_marking );
        t_771_generate_output_events( &output_events );
    }

    /* Transition move_L */
    if( t_777_enabled( prev_marking, &avail_marking ) &&
        t_777_events( &input_events ) &&
        t_777_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_777 = 1;
        t_777_remove_marks( &avail_marking );
        t_777_add_marks( &add_marking );
        t_777_generate_output_events( &output_events );
    }

    /* Transition obstacle_control */
    if( t_780_enabled( prev_marking, &avail_marking ) &&
        t_780_events( &input_events ) &&
        t_780_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_780 = 1;
        t_780_remove_marks( &avail_marking );
        t_780_add_marks( &add_marking );
        t_780_generate_output_events( &output_events );
    }

    /* Transition obstacle_control_2 */
    if( t_783_enabled( prev_marking, &avail_marking ) &&
        t_783_events( &input_events ) &&
        t_783_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_783 = 1;
        t_783_remove_marks( &avail_marking );
        t_783_add_marks( &add_marking );
        t_783_generate_output_events( &output_events );
    }

    /* Transition obstacle_control */
    if( t_786_enabled( prev_marking, &avail_marking ) &&
        t_786_events( &input_events ) &&
        t_786_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_786 = 1;
        t_786_remove_marks( &avail_marking );
        t_786_add_marks( &add_marking );
        t_786_generate_output_events( &output_events );
    }

    /* Transition obstacle_control_2 */
    if( t_787_enabled( prev_marking, &avail_marking ) &&
        t_787_events( &input_events ) &&
        t_787_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_787 = 1;
        t_787_remove_marks( &avail_marking );
        t_787_add_marks( &add_marking );
        t_787_generate_output_events( &output_events );
    }

    /* Transition up */
    if( t_824_enabled( prev_marking, &avail_marking ) &&
        t_824_events( &input_events ) &&
        t_824_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_824 = 1;
        t_824_remove_marks( &avail_marking );
        t_824_add_marks( &add_marking );
        t_824_generate_output_events( &output_events );
    }

    /* Transition down */
    if( t_825_enabled( prev_marking, &avail_marking ) &&
        t_825_events( &input_events ) &&
        t_825_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_825 = 1;
        t_825_remove_marks( &avail_marking );
        t_825_add_marks( &add_marking );
        t_825_generate_output_events( &output_events );
    }

    /* Transition up */
    if( t_836_enabled( prev_marking, &avail_marking ) &&
        t_836_events( &input_events ) &&
        t_836_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_836 = 1;
        t_836_remove_marks( &avail_marking );
        t_836_add_marks( &add_marking );
        t_836_generate_output_events( &output_events );
    }

    /* Transition down */
    if( t_837_enabled( prev_marking, &avail_marking ) &&
        t_837_events( &input_events ) &&
        t_837_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_837 = 1;
        t_837_remove_marks( &avail_marking );
        t_837_add_marks( &add_marking );
        t_837_generate_output_events( &output_events );
    }

    /* Transition up */
    if( t_843_enabled( prev_marking, &avail_marking ) &&
        t_843_events( &input_events ) &&
        t_843_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_843 = 1;
        t_843_remove_marks( &avail_marking );
        t_843_add_marks( &add_marking );
        t_843_generate_output_events( &output_events );
    }

    /* Transition down */
    if( t_844_enabled( prev_marking, &avail_marking ) &&
        t_844_events( &input_events ) &&
        t_844_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_844 = 1;
        t_844_remove_marks( &avail_marking );
        t_844_add_marks( &add_marking );
        t_844_generate_output_events( &output_events );
    }

    /* Transition down_1 */
    if( t_850_enabled( prev_marking, &avail_marking ) &&
        t_850_events( &input_events ) &&
        t_850_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_850 = 1;
        t_850_remove_marks( &avail_marking );
        t_850_add_marks( &add_marking );
        t_850_generate_output_events( &output_events );
    }

    /* Transition up_1 */
    if( t_851_enabled( prev_marking, &avail_marking ) &&
        t_851_events( &input_events ) &&
        t_851_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_851 = 1;
        t_851_remove_marks( &avail_marking );
        t_851_add_marks( &add_marking );
        t_851_generate_output_events( &output_events );
    }

    /* Transition down_1 */
    if( t_853_enabled( prev_marking, &avail_marking ) &&
        t_853_events( &input_events ) &&
        t_853_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_853 = 1;
        t_853_remove_marks( &avail_marking );
        t_853_add_marks( &add_marking );
        t_853_generate_output_events( &output_events );
    }

    /* Transition up_1 */
    if( t_854_enabled( prev_marking, &avail_marking ) &&
        t_854_events( &input_events ) &&
        t_854_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_854 = 1;
        t_854_remove_marks( &avail_marking );
        t_854_add_marks( &add_marking );
        t_854_generate_output_events( &output_events );
    }

    /* Transition down_1 */
    if( t_856_enabled( prev_marking, &avail_marking ) &&
        t_856_events( &input_events ) &&
        t_856_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_856 = 1;
        t_856_remove_marks( &avail_marking );
        t_856_add_marks( &add_marking );
        t_856_generate_output_events( &output_events );
    }

    /* Transition up_1 */
    if( t_857_enabled( prev_marking, &avail_marking ) &&
        t_857_events( &input_events ) &&
        t_857_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_857 = 1;
        t_857_remove_marks( &avail_marking );
        t_857_add_marks( &add_marking );
        t_857_generate_output_events( &output_events );
    }

    /* Transition increase_assist_1 */
    if( t_870_enabled( prev_marking, &avail_marking ) &&
        t_870_events( &input_events ) &&
        t_870_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_870 = 1;
        t_870_remove_marks( &avail_marking );
        t_870_add_marks( &add_marking );
        t_870_generate_output_events( &output_events );
    }

    /* Transition increase_assist_2 */
    if( t_873_enabled( prev_marking, &avail_marking ) &&
        t_873_events( &input_events ) &&
        t_873_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_873 = 1;
        t_873_remove_marks( &avail_marking );
        t_873_add_marks( &add_marking );
        t_873_generate_output_events( &output_events );
    }

    /* Transition increase_assist_3 */
    if( t_876_enabled( prev_marking, &avail_marking ) &&
        t_876_events( &input_events ) &&
        t_876_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_876 = 1;
        t_876_remove_marks( &avail_marking );
        t_876_add_marks( &add_marking );
        t_876_generate_output_events( &output_events );
    }

    /* Transition decrease_assist_3 */
    if( t_879_enabled( prev_marking, &avail_marking ) &&
        t_879_events( &input_events ) &&
        t_879_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_879 = 1;
        t_879_remove_marks( &avail_marking );
        t_879_add_marks( &add_marking );
        t_879_generate_output_events( &output_events );
    }

    /* Transition decrease_assist_2 */
    if( t_880_enabled( prev_marking, &avail_marking ) &&
        t_880_events( &input_events ) &&
        t_880_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_880 = 1;
        t_880_remove_marks( &avail_marking );
        t_880_add_marks( &add_marking );
        t_880_generate_output_events( &output_events );
    }

    /* Transition decrease_assist_1 */
    if( t_881_enabled( prev_marking, &avail_marking ) &&
        t_881_events( &input_events ) &&
        t_881_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_881 = 1;
        t_881_remove_marks( &avail_marking );
        t_881_add_marks( &add_marking );
        t_881_generate_output_events( &output_events );
    }

    /* Transition horn_ON_step */
    if( t_888_enabled( prev_marking, &avail_marking ) &&
        t_888_events( &input_events ) &&
        t_888_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_888 = 1;
        t_888_remove_marks( &avail_marking );
        t_888_add_marks( &add_marking );
        t_888_generate_output_events( &output_events );
    }

    /* Transition horn_OFF_joyInChg */
    if( t_895_enabled( prev_marking, &avail_marking ) &&
        t_895_events( &input_events ) &&
        t_895_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_895 = 1;
        t_895_remove_marks( &avail_marking );
        t_895_add_marks( &add_marking );
        t_895_generate_output_events( &output_events );
    }

    /* Transition horn_ON_obstacle */
    if( t_901_enabled( prev_marking, &avail_marking ) &&
        t_901_events( &input_events ) &&
        t_901_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_901 = 1;
        t_901_remove_marks( &avail_marking );
        t_901_add_marks( &add_marking );
        t_901_generate_output_events( &output_events );
    }

    add_ACM_signals_NetMarkings( &avail_marking, &add_marking );

    ACM_signals_GenerateTransitionActionOutputSignals( &tfired, &avail_marking, ev_out );
    ACM_signals_GeneratePlaceOutputSignals( &avail_marking, inputs, place_out, ev_out );
    ACM_signals_GenerateEventOutputSignals( &output_events, ev_out );
    ACM_signals_PutOutputSignals( place_out, ev_out, &output_events );
    *prev_marking = avail_marking;
}

ACM_signals_TransitionFiring* get_ACM_signals_TransitionFiring()
{
    return &tfired;
}

