/* Net ACM_signals - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <string.h>
#include <stdlib.h>
#include "net_types.h"


#if defined(HTTP_SERVER) || defined(DBG_INFO)

static iopt_param_info ACM_signals_input_info[] = {
    { "inChg", 0 },
    { "btnF_R", 0 },
    { "btnF", 0 },
    { "btnF_L", 0 },
    { "btnL", 0 },
    { "btnR", 0 },
    { "btnB", 0 },
    { "btnB_R", 0 },
    { "btnB_L", 0 },
    { "btnHorn", 0 },
    { "btnInc", 0 },
    { "btnDec", 0 },
    { "front_sensor_dist", 0 },
    { "back_sensor_dist", 0 },
    { "left_sensor_dist", 0 },
    { "right_sensor_dist", 0 },
    { "dist_min", 0 },
    { "btnAssist_mode", 0 },
    { "pitch", 0 },
    { NULL, 0 }
};

static iopt_param_info ACM_signals_output_info[] = {
    { "tpi_inChg", 0 },
    { "ForwardQ", 0 },
    { "ReverseQ", 0 },
    { "RightQ", 0 },
    { "LeftQ", 0 },
    { "Horn", 0 },
    { "speedDial", 0 },
    { "back_alert", 0 },
    { "left_alert", 0 },
    { "right_alert", 0 },
    { "front_alert", 0 },
    { "Assist_mode", 0 },
    { "pitch_alert", 0 },
    { NULL, 0 }
};

static iopt_param_info ACM_signals_marking_info[] = {
    { "p_306", 0 },
    { "p_308", 0 },
    { "p_386", 0 },
    { "p_387", 0 },
    { "p_448", 0 },
    { "p_495", 0 },
    { "p_496", 0 },
    { "p_502", 0 },
    { "p_503", 0 },
    { "p_504", 0 },
    { "p_505", 0 },
    { "p_545", 0 },
    { "p_546", 0 },
    { "p_547", 0 },
    { "p_548", 0 },
    { "p_567", 0 },
    { "p_568", 0 },
    { "p_569", 0 },
    { "p_570", 0 },
    { "p_589", 0 },
    { "p_590", 0 },
    { "p_591", 0 },
    { "p_592", 0 },
    { "p_611", 0 },
    { "p_612", 0 },
    { "p_634", 0 },
    { "p_635", 0 },
    { "p_697", 0 },
    { "p_710", 0 },
    { "p_714", 0 },
    { "p_726", 0 },
    { "p_729", 0 },
    { "p_822", 0 },
    { "p_823", 0 },
    { "p_835", 0 },
    { "p_842", 0 },
    { "p_849", 0 },
    { "p_852", 0 },
    { "p_855", 0 },
    { NULL, 0 }
};

static iopt_param_info ACM_signals_tfired_info[] = {
    { "t_305", 0 },
    { "t_322", 0 },
    { "t_398", 0 },
    { "t_473", 0 },
    { "t_482", 0 },
    { "t_485", 0 },
    { "t_494", 0 },
    { "t_497", 0 },
    { "t_506", 0 },
    { "t_507", 0 },
    { "t_508", 0 },
    { "t_509", 0 },
    { "t_510", 0 },
    { "t_511", 0 },
    { "t_549", 0 },
    { "t_550", 0 },
    { "t_551", 0 },
    { "t_552", 0 },
    { "t_553", 0 },
    { "t_554", 0 },
    { "t_571", 0 },
    { "t_572", 0 },
    { "t_573", 0 },
    { "t_574", 0 },
    { "t_575", 0 },
    { "t_576", 0 },
    { "t_593", 0 },
    { "t_594", 0 },
    { "t_595", 0 },
    { "t_596", 0 },
    { "t_597", 0 },
    { "t_598", 0 },
    { "t_615", 0 },
    { "t_616", 0 },
    { "t_643", 0 },
    { "t_651", 0 },
    { "t_652", 0 },
    { "t_673", 0 },
    { "t_685", 0 },
    { "t_686", 0 },
    { "t_694", 0 },
    { "t_707", 0 },
    { "t_711", 0 },
    { "t_712", 0 },
    { "t_713", 0 },
    { "t_728", 0 },
    { "t_730", 0 },
    { "t_731", 0 },
    { "t_742", 0 },
    { "t_745", 0 },
    { "t_746", 0 },
    { "t_752", 0 },
    { "t_757", 0 },
    { "t_765", 0 },
    { "t_768", 0 },
    { "t_771", 0 },
    { "t_777", 0 },
    { "t_780", 0 },
    { "t_783", 0 },
    { "t_786", 0 },
    { "t_787", 0 },
    { "t_824", 0 },
    { "t_825", 0 },
    { "t_836", 0 },
    { "t_837", 0 },
    { "t_843", 0 },
    { "t_844", 0 },
    { "t_850", 0 },
    { "t_851", 0 },
    { "t_853", 0 },
    { "t_854", 0 },
    { "t_856", 0 },
    { "t_857", 0 },
    { "t_870", 0 },
    { "t_873", 0 },
    { "t_876", 0 },
    { "t_879", 0 },
    { "t_880", 0 },
    { "t_881", 0 },
    { "t_888", 0 },
    { "t_895", 0 },
    { "t_901", 0 },
    { NULL, 0 }
};

iopt_param_info* get_ACM_signals_InputInfo()
{
    ACM_signals_InputSignals* inputs = get_ACM_signals_InputSignals();
    ACM_signals_input_info[0].value = inputs->inChg;
    ACM_signals_input_info[1].value = inputs->btnF_R;
    ACM_signals_input_info[2].value = inputs->btnF;
    ACM_signals_input_info[3].value = inputs->btnF_L;
    ACM_signals_input_info[4].value = inputs->btnL;
    ACM_signals_input_info[5].value = inputs->btnR;
    ACM_signals_input_info[6].value = inputs->btnB;
    ACM_signals_input_info[7].value = inputs->btnB_R;
    ACM_signals_input_info[8].value = inputs->btnB_L;
    ACM_signals_input_info[9].value = inputs->btnHorn;
    ACM_signals_input_info[10].value = inputs->btnInc;
    ACM_signals_input_info[11].value = inputs->btnDec;
    ACM_signals_input_info[12].value = inputs->front_sensor_dist;
    ACM_signals_input_info[13].value = inputs->back_sensor_dist;
    ACM_signals_input_info[14].value = inputs->left_sensor_dist;
    ACM_signals_input_info[15].value = inputs->right_sensor_dist;
    ACM_signals_input_info[16].value = inputs->dist_min;
    ACM_signals_input_info[17].value = inputs->btnAssist_mode;
    ACM_signals_input_info[18].value = inputs->pitch;
    return ACM_signals_input_info;
}

iopt_param_info* get_ACM_signals_OutputInfo()
{
    ACM_signals_PlaceOutputSignals* place_out = get_ACM_signals_PlaceOutputSignals();
    ACM_signals_EventOutputSignals* ev_out = get_ACM_signals_EventOutputSignals();
    ACM_signals_output_info[0].value = place_out->tpi_inChg;
    ACM_signals_output_info[1].value = place_out->ForwardQ;
    ACM_signals_output_info[2].value = place_out->ReverseQ;
    ACM_signals_output_info[3].value = place_out->RightQ;
    ACM_signals_output_info[4].value = place_out->LeftQ;
    ACM_signals_output_info[5].value = place_out->Horn;
    ACM_signals_output_info[6].value = place_out->speedDial;
    ACM_signals_output_info[7].value = place_out->back_alert;
    ACM_signals_output_info[8].value = place_out->left_alert;
    ACM_signals_output_info[9].value = place_out->right_alert;
    ACM_signals_output_info[10].value = place_out->front_alert;
    ACM_signals_output_info[11].value = place_out->Assist_mode;
    ACM_signals_output_info[12].value = place_out->pitch_alert;
    return ACM_signals_output_info;
}

iopt_param_info* get_ACM_signals_MarkingInfo()
{
    ACM_signals_NetMarking* marking = get_ACM_signals_NetMarking();
    ACM_signals_marking_info[0].value = marking->p_306;
    ACM_signals_marking_info[1].value = marking->p_308;
    ACM_signals_marking_info[2].value = marking->p_386;
    ACM_signals_marking_info[3].value = marking->p_387;
    ACM_signals_marking_info[4].value = marking->p_448;
    ACM_signals_marking_info[5].value = marking->p_495;
    ACM_signals_marking_info[6].value = marking->p_496;
    ACM_signals_marking_info[7].value = marking->p_502;
    ACM_signals_marking_info[8].value = marking->p_503;
    ACM_signals_marking_info[9].value = marking->p_504;
    ACM_signals_marking_info[10].value = marking->p_505;
    ACM_signals_marking_info[11].value = marking->p_545;
    ACM_signals_marking_info[12].value = marking->p_546;
    ACM_signals_marking_info[13].value = marking->p_547;
    ACM_signals_marking_info[14].value = marking->p_548;
    ACM_signals_marking_info[15].value = marking->p_567;
    ACM_signals_marking_info[16].value = marking->p_568;
    ACM_signals_marking_info[17].value = marking->p_569;
    ACM_signals_marking_info[18].value = marking->p_570;
    ACM_signals_marking_info[19].value = marking->p_589;
    ACM_signals_marking_info[20].value = marking->p_590;
    ACM_signals_marking_info[21].value = marking->p_591;
    ACM_signals_marking_info[22].value = marking->p_592;
    ACM_signals_marking_info[23].value = marking->p_611;
    ACM_signals_marking_info[24].value = marking->p_612;
    ACM_signals_marking_info[25].value = marking->p_634;
    ACM_signals_marking_info[26].value = marking->p_635;
    ACM_signals_marking_info[27].value = marking->p_697;
    ACM_signals_marking_info[28].value = marking->p_710;
    ACM_signals_marking_info[29].value = marking->p_714;
    ACM_signals_marking_info[30].value = marking->p_726;
    ACM_signals_marking_info[31].value = marking->p_729;
    ACM_signals_marking_info[32].value = marking->p_822;
    ACM_signals_marking_info[33].value = marking->p_823;
    ACM_signals_marking_info[34].value = marking->p_835;
    ACM_signals_marking_info[35].value = marking->p_842;
    ACM_signals_marking_info[36].value = marking->p_849;
    ACM_signals_marking_info[37].value = marking->p_852;
    ACM_signals_marking_info[38].value = marking->p_855;
    return ACM_signals_marking_info;
}

void force_ACM_signals_Inputs( iopt_param_info fv[],
        ACM_signals_InputSignals* in )
{
    int i;
    for( i = 0; fv[i].name != NULL; ++i ) {
        if( strcmp( fv[i].name, ACM_signals_input_info[0].name ) == 0 )
           in->inChg = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[1].name ) == 0 )
           in->btnF_R = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[2].name ) == 0 )
           in->btnF = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[3].name ) == 0 )
           in->btnF_L = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[4].name ) == 0 )
           in->btnL = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[5].name ) == 0 )
           in->btnR = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[6].name ) == 0 )
           in->btnB = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[7].name ) == 0 )
           in->btnB_R = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[8].name ) == 0 )
           in->btnB_L = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[9].name ) == 0 )
           in->btnHorn = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[10].name ) == 0 )
           in->btnInc = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[11].name ) == 0 )
           in->btnDec = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[12].name ) == 0 )
           in->front_sensor_dist = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[13].name ) == 0 )
           in->back_sensor_dist = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[14].name ) == 0 )
           in->left_sensor_dist = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[15].name ) == 0 )
           in->right_sensor_dist = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[16].name ) == 0 )
           in->dist_min = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[17].name ) == 0 )
           in->btnAssist_mode = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_input_info[18].name ) == 0 )
           in->pitch = fv[i].value;
    }
}

void force_ACM_signals_Outputs( iopt_param_info fv[],
        ACM_signals_PlaceOutputSignals* place_out,
        ACM_signals_EventOutputSignals* ev_out )
{
    int i;
    for( i = 0; fv[i].name != NULL; ++i ) {
        if( strcmp( fv[i].name, ACM_signals_output_info[0].name ) == 0 )
           place_out->tpi_inChg = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_output_info[1].name ) == 0 )
           place_out->ForwardQ = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_output_info[2].name ) == 0 )
           place_out->ReverseQ = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_output_info[3].name ) == 0 )
           place_out->RightQ = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_output_info[4].name ) == 0 )
           place_out->LeftQ = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_output_info[5].name ) == 0 )
           place_out->Horn = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_output_info[6].name ) == 0 )
           place_out->speedDial = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_output_info[7].name ) == 0 )
           place_out->back_alert = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_output_info[8].name ) == 0 )
           place_out->left_alert = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_output_info[9].name ) == 0 )
           place_out->right_alert = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_output_info[10].name ) == 0 )
           place_out->front_alert = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_output_info[11].name ) == 0 )
           place_out->Assist_mode = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_output_info[12].name ) == 0 )
           place_out->pitch_alert = fv[i].value;
    }
}

void force_ACM_signals_Marking( iopt_param_info fv[],
        ACM_signals_NetMarking* m )
{
    int i;
    for( i = 0; fv[i].name != NULL; ++i ) {
        if( strcmp( fv[i].name, ACM_signals_marking_info[0].name ) == 0 )
           m->p_306 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[1].name ) == 0 )
           m->p_308 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[2].name ) == 0 )
           m->p_386 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[3].name ) == 0 )
           m->p_387 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[4].name ) == 0 )
           m->p_448 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[5].name ) == 0 )
           m->p_495 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[6].name ) == 0 )
           m->p_496 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[7].name ) == 0 )
           m->p_502 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[8].name ) == 0 )
           m->p_503 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[9].name ) == 0 )
           m->p_504 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[10].name ) == 0 )
           m->p_505 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[11].name ) == 0 )
           m->p_545 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[12].name ) == 0 )
           m->p_546 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[13].name ) == 0 )
           m->p_547 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[14].name ) == 0 )
           m->p_548 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[15].name ) == 0 )
           m->p_567 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[16].name ) == 0 )
           m->p_568 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[17].name ) == 0 )
           m->p_569 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[18].name ) == 0 )
           m->p_570 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[19].name ) == 0 )
           m->p_589 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[20].name ) == 0 )
           m->p_590 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[21].name ) == 0 )
           m->p_591 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[22].name ) == 0 )
           m->p_592 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[23].name ) == 0 )
           m->p_611 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[24].name ) == 0 )
           m->p_612 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[25].name ) == 0 )
           m->p_634 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[26].name ) == 0 )
           m->p_635 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[27].name ) == 0 )
           m->p_697 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[28].name ) == 0 )
           m->p_710 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[29].name ) == 0 )
           m->p_714 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[30].name ) == 0 )
           m->p_726 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[31].name ) == 0 )
           m->p_729 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[32].name ) == 0 )
           m->p_822 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[33].name ) == 0 )
           m->p_823 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[34].name ) == 0 )
           m->p_835 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[35].name ) == 0 )
           m->p_842 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[36].name ) == 0 )
           m->p_849 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[37].name ) == 0 )
           m->p_852 = fv[i].value;
        else if( strcmp( fv[i].name, ACM_signals_marking_info[38].name ) == 0 )
           m->p_855 = fv[i].value;
    }
}

iopt_param_info* get_ACM_signals_TFiredInfo()
{
    ACM_signals_TransitionFiring* tfired = get_ACM_signals_TransitionFiring();
    ACM_signals_tfired_info[0].value = tfired->t_305;
    ACM_signals_tfired_info[1].value = tfired->t_322;
    ACM_signals_tfired_info[2].value = tfired->t_398;
    ACM_signals_tfired_info[3].value = tfired->t_473;
    ACM_signals_tfired_info[4].value = tfired->t_482;
    ACM_signals_tfired_info[5].value = tfired->t_485;
    ACM_signals_tfired_info[6].value = tfired->t_494;
    ACM_signals_tfired_info[7].value = tfired->t_497;
    ACM_signals_tfired_info[8].value = tfired->t_506;
    ACM_signals_tfired_info[9].value = tfired->t_507;
    ACM_signals_tfired_info[10].value = tfired->t_508;
    ACM_signals_tfired_info[11].value = tfired->t_509;
    ACM_signals_tfired_info[12].value = tfired->t_510;
    ACM_signals_tfired_info[13].value = tfired->t_511;
    ACM_signals_tfired_info[14].value = tfired->t_549;
    ACM_signals_tfired_info[15].value = tfired->t_550;
    ACM_signals_tfired_info[16].value = tfired->t_551;
    ACM_signals_tfired_info[17].value = tfired->t_552;
    ACM_signals_tfired_info[18].value = tfired->t_553;
    ACM_signals_tfired_info[19].value = tfired->t_554;
    ACM_signals_tfired_info[20].value = tfired->t_571;
    ACM_signals_tfired_info[21].value = tfired->t_572;
    ACM_signals_tfired_info[22].value = tfired->t_573;
    ACM_signals_tfired_info[23].value = tfired->t_574;
    ACM_signals_tfired_info[24].value = tfired->t_575;
    ACM_signals_tfired_info[25].value = tfired->t_576;
    ACM_signals_tfired_info[26].value = tfired->t_593;
    ACM_signals_tfired_info[27].value = tfired->t_594;
    ACM_signals_tfired_info[28].value = tfired->t_595;
    ACM_signals_tfired_info[29].value = tfired->t_596;
    ACM_signals_tfired_info[30].value = tfired->t_597;
    ACM_signals_tfired_info[31].value = tfired->t_598;
    ACM_signals_tfired_info[32].value = tfired->t_615;
    ACM_signals_tfired_info[33].value = tfired->t_616;
    ACM_signals_tfired_info[34].value = tfired->t_643;
    ACM_signals_tfired_info[35].value = tfired->t_651;
    ACM_signals_tfired_info[36].value = tfired->t_652;
    ACM_signals_tfired_info[37].value = tfired->t_673;
    ACM_signals_tfired_info[38].value = tfired->t_685;
    ACM_signals_tfired_info[39].value = tfired->t_686;
    ACM_signals_tfired_info[40].value = tfired->t_694;
    ACM_signals_tfired_info[41].value = tfired->t_707;
    ACM_signals_tfired_info[42].value = tfired->t_711;
    ACM_signals_tfired_info[43].value = tfired->t_712;
    ACM_signals_tfired_info[44].value = tfired->t_713;
    ACM_signals_tfired_info[45].value = tfired->t_728;
    ACM_signals_tfired_info[46].value = tfired->t_730;
    ACM_signals_tfired_info[47].value = tfired->t_731;
    ACM_signals_tfired_info[48].value = tfired->t_742;
    ACM_signals_tfired_info[49].value = tfired->t_745;
    ACM_signals_tfired_info[50].value = tfired->t_746;
    ACM_signals_tfired_info[51].value = tfired->t_752;
    ACM_signals_tfired_info[52].value = tfired->t_757;
    ACM_signals_tfired_info[53].value = tfired->t_765;
    ACM_signals_tfired_info[54].value = tfired->t_768;
    ACM_signals_tfired_info[55].value = tfired->t_771;
    ACM_signals_tfired_info[56].value = tfired->t_777;
    ACM_signals_tfired_info[57].value = tfired->t_780;
    ACM_signals_tfired_info[58].value = tfired->t_783;
    ACM_signals_tfired_info[59].value = tfired->t_786;
    ACM_signals_tfired_info[60].value = tfired->t_787;
    ACM_signals_tfired_info[61].value = tfired->t_824;
    ACM_signals_tfired_info[62].value = tfired->t_825;
    ACM_signals_tfired_info[63].value = tfired->t_836;
    ACM_signals_tfired_info[64].value = tfired->t_837;
    ACM_signals_tfired_info[65].value = tfired->t_843;
    ACM_signals_tfired_info[66].value = tfired->t_844;
    ACM_signals_tfired_info[67].value = tfired->t_850;
    ACM_signals_tfired_info[68].value = tfired->t_851;
    ACM_signals_tfired_info[69].value = tfired->t_853;
    ACM_signals_tfired_info[70].value = tfired->t_854;
    ACM_signals_tfired_info[71].value = tfired->t_856;
    ACM_signals_tfired_info[72].value = tfired->t_857;
    ACM_signals_tfired_info[73].value = tfired->t_870;
    ACM_signals_tfired_info[74].value = tfired->t_873;
    ACM_signals_tfired_info[75].value = tfired->t_876;
    ACM_signals_tfired_info[76].value = tfired->t_879;
    ACM_signals_tfired_info[77].value = tfired->t_880;
    ACM_signals_tfired_info[78].value = tfired->t_881;
    ACM_signals_tfired_info[79].value = tfired->t_888;
    ACM_signals_tfired_info[80].value = tfired->t_895;
    ACM_signals_tfired_info[81].value = tfired->t_901;
    return ACM_signals_tfired_info;
}

#endif
