/* Net ACM_signals - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#ifndef __ACM_signals_DEFS
#define __ACM_signals_DEFS


//#define HTTP_SERVER

#define TRACE_CONT_RUN       (-1)
#define TRACE_PAUSE          0
#define TRACE_SINGLE_STEP    1
#define TRACE_N_STEPS(n)     (n)

#define MODEL_NAME		ACM_signals
#define MODEL_NAME_STR		"ACM_signals"
#define MODEL_VERSION		"2025-09-12 13:55:59"
#define MODEL_N_INPUTS		19
#define MODEL_N_OUTPUTS		13
#define MODEL_N_PLACES		39
#define MODEL_N_TRANSITIONS	82

#ifdef __cplusplus
extern "C" {
#endif

extern int trace_control;

typedef struct {
    unsigned int p_306: 1; /* Place tpi_inChg */
    unsigned int p_308: 1; /* Place joy_inChg */
    unsigned int p_386: 1; /* Place Left */
    unsigned int p_387: 1; /* Place Backward */
    unsigned int p_448: 1; /* Place left_side */
    unsigned int p_495: 1; /* Place horn_ON_button */
    unsigned int p_496: 1; /* Place horn_OFF */
    unsigned int p_502: 1; /* Place speed_25 */
    unsigned int p_503: 1; /* Place speed_50 */
    unsigned int p_504: 1; /* Place speed_75 */
    unsigned int p_505: 1; /* Place speed_100 */
    unsigned int p_545: 1; /* Place back_0 */
    unsigned int p_546: 1; /* Place back_1 */
    unsigned int p_547: 1; /* Place back_2 */
    unsigned int p_548: 1; /* Place back_3 */
    unsigned int p_567: 1; /* Place left_0 */
    unsigned int p_568: 1; /* Place left_1 */
    unsigned int p_569: 1; /* Place left_2 */
    unsigned int p_570: 1; /* Place left_3 */
    unsigned int p_589: 1; /* Place right_0 */
    unsigned int p_590: 1; /* Place right_1 */
    unsigned int p_591: 1; /* Place right_2 */
    unsigned int p_592: 1; /* Place right_3 */
    unsigned int p_611: 1; /* Place front_flat */
    unsigned int p_612: 1; /* Place front_step */
    unsigned int p_634: 1; /* Place Assist_mode_ON */
    unsigned int p_635: 1; /* Place Assist_mode_OFF */
    unsigned int p_697: 1; /* Place back_side */
    unsigned int p_710: 1; /* Place Forward */
    unsigned int p_714: 1; /* Place front_side */
    unsigned int p_726: 1; /* Place Right */
    unsigned int p_729: 1; /* Place right_side */
    unsigned int p_822: 1; /* Place leveled */
    unsigned int p_823: 1; /* Place tilted_up_1 */
    unsigned int p_835: 1; /* Place tilted_up_2 */
    unsigned int p_842: 1; /* Place tilted_up_3 */
    unsigned int p_849: 1; /* Place tilted_down_1 */
    unsigned int p_852: 1; /* Place tilted_down_2 */
    unsigned int p_855: 1; /* Place tilted_down_3 */
    unsigned int padding: 1;
} ACM_signals_NetMarking;


typedef struct {
    unsigned int inChg : 1;
    unsigned int btnF_R : 1;
    unsigned int btnF : 1;
    unsigned int btnF_L : 1;
    unsigned int btnL : 1;
    unsigned int btnR : 1;
    unsigned int btnB : 1;
    unsigned int btnB_R : 1;
    unsigned int btnB_L : 1;
    unsigned int btnHorn : 1;
    unsigned int btnInc : 1;
    unsigned int btnDec : 1;
    unsigned int front_sensor_dist : 7;
    unsigned int back_sensor_dist : 8;
    unsigned int left_sensor_dist : 8;
    unsigned int right_sensor_dist : 8;
    unsigned int dist_min : 6;
    unsigned int btnAssist_mode : 1;
    int pitch : 6;
} ACM_signals_InputSignals;


typedef struct {
    unsigned int btnInc_up : 1;
    unsigned int btnDec_up : 1;
    unsigned int btnAssist_mode_up : 1;
} ACM_signals_InputSignalEvents;


typedef struct {
} ACM_signals_OutputSignalEvents;


typedef struct {
    unsigned int tpi_inChg : 1;
    unsigned int ForwardQ : 1;
    unsigned int ReverseQ : 1;
    unsigned int RightQ : 1;
    unsigned int LeftQ : 1;
    unsigned int Horn : 1;
    unsigned int speedDial : 3;
    unsigned int back_alert : 2;
    unsigned int left_alert : 2;
    unsigned int right_alert : 2;
    unsigned int front_alert : 1;
    unsigned int Assist_mode : 1;
    int pitch_alert : 3;
} ACM_signals_PlaceOutputSignals;


typedef struct {
} ACM_signals_EventOutputSignals;


typedef struct {
    unsigned int t_305 : 1; /* change_Joy */
    unsigned int t_322 : 1; /* change_TPI */
    unsigned int t_398 : 1; /* stop_RightON */
    unsigned int t_473 : 1; /* stop_FrontON */
    unsigned int t_482 : 1; /* stop_LeftOFF */
    unsigned int t_485 : 1; /* stop_BackOFF */
    unsigned int t_494 : 1; /* horn_OFF */
    unsigned int t_497 : 1; /* horn_ON */
    unsigned int t_506 : 1; /* increase */
    unsigned int t_507 : 1; /* decrease */
    unsigned int t_508 : 1; /* decrease_2 */
    unsigned int t_509 : 1; /* increase_2 */
    unsigned int t_510 : 1; /* decrease_3 */
    unsigned int t_511 : 1; /* increase_3 */
    unsigned int t_549 : 1; /* closer */
    unsigned int t_550 : 1; /* further */
    unsigned int t_551 : 1; /* further */
    unsigned int t_552 : 1; /* closer */
    unsigned int t_553 : 1; /* further */
    unsigned int t_554 : 1; /* closer */
    unsigned int t_571 : 1; /* closer_2 */
    unsigned int t_572 : 1; /* further_2 */
    unsigned int t_573 : 1; /* further_3 */
    unsigned int t_574 : 1; /* closer_3 */
    unsigned int t_575 : 1; /* further_4 */
    unsigned int t_576 : 1; /* closer_4 */
    unsigned int t_593 : 1; /* closer_5 */
    unsigned int t_594 : 1; /* further_5 */
    unsigned int t_595 : 1; /* further_6 */
    unsigned int t_596 : 1; /* closer_6 */
    unsigned int t_597 : 1; /* further_7 */
    unsigned int t_598 : 1; /* closer_7 */
    unsigned int t_615 : 1; /* step_detect */
    unsigned int t_616 : 1; /* no_step */
    unsigned int t_643 : 1; /* change_ON */
    unsigned int t_651 : 1; /* change_joyInChg */
    unsigned int t_652 : 1; /* change_OFF */
    unsigned int t_673 : 1; /* step_control */
    unsigned int t_685 : 1; /* stop_joyInChg */
    unsigned int t_686 : 1; /* stop_joyInChg */
    unsigned int t_694 : 1; /* obstacle_control */
    unsigned int t_707 : 1; /* move_B */
    unsigned int t_711 : 1; /* stop_BackON */
    unsigned int t_712 : 1; /* stop_FrontOFF */
    unsigned int t_713 : 1; /* stop_joyInChg */
    unsigned int t_728 : 1; /* stop_LeftON */
    unsigned int t_730 : 1; /* stop_RightOFF */
    unsigned int t_731 : 1; /* stop_joyInChg */
    unsigned int t_742 : 1; /* move_R */
    unsigned int t_745 : 1; /* stop_FrontBackON */
    unsigned int t_746 : 1; /* stop_FrontBackON */
    unsigned int t_752 : 1; /* stop_LeftRightON */
    unsigned int t_757 : 1; /* stop_LeftRightON */
    unsigned int t_765 : 1; /* step_control */
    unsigned int t_768 : 1; /* step_control */
    unsigned int t_771 : 1; /* move_F */
    unsigned int t_777 : 1; /* move_L */
    unsigned int t_780 : 1; /* obstacle_control */
    unsigned int t_783 : 1; /* obstacle_control_2 */
    unsigned int t_786 : 1; /* obstacle_control */
    unsigned int t_787 : 1; /* obstacle_control_2 */
    unsigned int t_824 : 1; /* up */
    unsigned int t_825 : 1; /* down */
    unsigned int t_836 : 1; /* up */
    unsigned int t_837 : 1; /* down */
    unsigned int t_843 : 1; /* up */
    unsigned int t_844 : 1; /* down */
    unsigned int t_850 : 1; /* down_1 */
    unsigned int t_851 : 1; /* up_1 */
    unsigned int t_853 : 1; /* down_1 */
    unsigned int t_854 : 1; /* up_1 */
    unsigned int t_856 : 1; /* down_1 */
    unsigned int t_857 : 1; /* up_1 */
    unsigned int t_870 : 1; /* increase_assist_1 */
    unsigned int t_873 : 1; /* increase_assist_2 */
    unsigned int t_876 : 1; /* increase_assist_3 */
    unsigned int t_879 : 1; /* decrease_assist_3 */
    unsigned int t_880 : 1; /* decrease_assist_2 */
    unsigned int t_881 : 1; /* decrease_assist_1 */
    unsigned int t_888 : 1; /* horn_ON_step */
    unsigned int t_895 : 1; /* horn_OFF_joyInChg */
    unsigned int t_901 : 1; /* horn_ON_obstacle */
    unsigned int count: 8;
} ACM_signals_TransitionFiring;

/* Array declarations: */


/* Runtime text info: */
typedef struct {
#ifdef __cplusplus
    const
#endif
    char* name;
    int value;
} iopt_param_info;

extern iopt_param_info* get_ACM_signals_InputInfo();
extern iopt_param_info* get_ACM_signals_OutputInfo();
extern iopt_param_info* get_ACM_signals_MarkingInfo();
extern iopt_param_info* get_ACM_signals_TFiredInfo();
extern void force_ACM_signals_Inputs( iopt_param_info fv[], ACM_signals_InputSignals* in );
extern void force_ACM_signals_Outputs( iopt_param_info fv[], ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void force_ACM_signals_Marking( iopt_param_info fv[], ACM_signals_NetMarking* m );


extern void createInitial_ACM_signals_NetMarking( ACM_signals_NetMarking* init_marking );
extern void createEmpty_ACM_signals_NetMarking( ACM_signals_NetMarking* empty_marking );
extern void add_ACM_signals_NetMarkings( ACM_signals_NetMarking* dest_marking, ACM_signals_NetMarking* source_marking );

extern void init_ACM_signals_OutputSignals( ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );

/* Transition 305 - change_Joy */
extern int  t_305_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_305_events( ACM_signals_InputSignalEvents* events );
extern int  t_305_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_305_remove_marks( ACM_signals_NetMarking* marking );
extern void t_305_add_marks( ACM_signals_NetMarking* marking );
extern void t_305_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 322 - change_TPI */
extern int  t_322_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_322_events( ACM_signals_InputSignalEvents* events );
extern int  t_322_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_322_remove_marks( ACM_signals_NetMarking* marking );
extern void t_322_add_marks( ACM_signals_NetMarking* marking );
extern void t_322_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 398 - stop_RightON */
extern int  t_398_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_398_events( ACM_signals_InputSignalEvents* events );
extern int  t_398_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_398_remove_marks( ACM_signals_NetMarking* marking );
extern void t_398_add_marks( ACM_signals_NetMarking* marking );
extern void t_398_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 473 - stop_FrontON */
extern int  t_473_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_473_events( ACM_signals_InputSignalEvents* events );
extern int  t_473_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_473_remove_marks( ACM_signals_NetMarking* marking );
extern void t_473_add_marks( ACM_signals_NetMarking* marking );
extern void t_473_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 482 - stop_LeftOFF */
extern int  t_482_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_482_events( ACM_signals_InputSignalEvents* events );
extern int  t_482_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_482_remove_marks( ACM_signals_NetMarking* marking );
extern void t_482_add_marks( ACM_signals_NetMarking* marking );
extern void t_482_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 485 - stop_BackOFF */
extern int  t_485_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_485_events( ACM_signals_InputSignalEvents* events );
extern int  t_485_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_485_remove_marks( ACM_signals_NetMarking* marking );
extern void t_485_add_marks( ACM_signals_NetMarking* marking );
extern void t_485_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 494 - horn_OFF */
extern int  t_494_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_494_events( ACM_signals_InputSignalEvents* events );
extern int  t_494_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_494_remove_marks( ACM_signals_NetMarking* marking );
extern void t_494_add_marks( ACM_signals_NetMarking* marking );
extern void t_494_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 497 - horn_ON */
extern int  t_497_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_497_events( ACM_signals_InputSignalEvents* events );
extern int  t_497_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_497_remove_marks( ACM_signals_NetMarking* marking );
extern void t_497_add_marks( ACM_signals_NetMarking* marking );
extern void t_497_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 506 - increase */
extern int  t_506_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_506_events( ACM_signals_InputSignalEvents* events );
extern int  t_506_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_506_remove_marks( ACM_signals_NetMarking* marking );
extern void t_506_add_marks( ACM_signals_NetMarking* marking );
extern void t_506_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 507 - decrease */
extern int  t_507_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_507_events( ACM_signals_InputSignalEvents* events );
extern int  t_507_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_507_remove_marks( ACM_signals_NetMarking* marking );
extern void t_507_add_marks( ACM_signals_NetMarking* marking );
extern void t_507_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 508 - decrease_2 */
extern int  t_508_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_508_events( ACM_signals_InputSignalEvents* events );
extern int  t_508_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_508_remove_marks( ACM_signals_NetMarking* marking );
extern void t_508_add_marks( ACM_signals_NetMarking* marking );
extern void t_508_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 509 - increase_2 */
extern int  t_509_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_509_events( ACM_signals_InputSignalEvents* events );
extern int  t_509_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_509_remove_marks( ACM_signals_NetMarking* marking );
extern void t_509_add_marks( ACM_signals_NetMarking* marking );
extern void t_509_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 510 - decrease_3 */
extern int  t_510_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_510_events( ACM_signals_InputSignalEvents* events );
extern int  t_510_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_510_remove_marks( ACM_signals_NetMarking* marking );
extern void t_510_add_marks( ACM_signals_NetMarking* marking );
extern void t_510_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 511 - increase_3 */
extern int  t_511_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_511_events( ACM_signals_InputSignalEvents* events );
extern int  t_511_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_511_remove_marks( ACM_signals_NetMarking* marking );
extern void t_511_add_marks( ACM_signals_NetMarking* marking );
extern void t_511_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 549 - closer */
extern int  t_549_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_549_events( ACM_signals_InputSignalEvents* events );
extern int  t_549_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_549_remove_marks( ACM_signals_NetMarking* marking );
extern void t_549_add_marks( ACM_signals_NetMarking* marking );
extern void t_549_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 550 - further */
extern int  t_550_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_550_events( ACM_signals_InputSignalEvents* events );
extern int  t_550_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_550_remove_marks( ACM_signals_NetMarking* marking );
extern void t_550_add_marks( ACM_signals_NetMarking* marking );
extern void t_550_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 551 - further */
extern int  t_551_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_551_events( ACM_signals_InputSignalEvents* events );
extern int  t_551_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_551_remove_marks( ACM_signals_NetMarking* marking );
extern void t_551_add_marks( ACM_signals_NetMarking* marking );
extern void t_551_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 552 - closer */
extern int  t_552_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_552_events( ACM_signals_InputSignalEvents* events );
extern int  t_552_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_552_remove_marks( ACM_signals_NetMarking* marking );
extern void t_552_add_marks( ACM_signals_NetMarking* marking );
extern void t_552_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 553 - further */
extern int  t_553_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_553_events( ACM_signals_InputSignalEvents* events );
extern int  t_553_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_553_remove_marks( ACM_signals_NetMarking* marking );
extern void t_553_add_marks( ACM_signals_NetMarking* marking );
extern void t_553_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 554 - closer */
extern int  t_554_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_554_events( ACM_signals_InputSignalEvents* events );
extern int  t_554_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_554_remove_marks( ACM_signals_NetMarking* marking );
extern void t_554_add_marks( ACM_signals_NetMarking* marking );
extern void t_554_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 571 - closer_2 */
extern int  t_571_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_571_events( ACM_signals_InputSignalEvents* events );
extern int  t_571_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_571_remove_marks( ACM_signals_NetMarking* marking );
extern void t_571_add_marks( ACM_signals_NetMarking* marking );
extern void t_571_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 572 - further_2 */
extern int  t_572_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_572_events( ACM_signals_InputSignalEvents* events );
extern int  t_572_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_572_remove_marks( ACM_signals_NetMarking* marking );
extern void t_572_add_marks( ACM_signals_NetMarking* marking );
extern void t_572_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 573 - further_3 */
extern int  t_573_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_573_events( ACM_signals_InputSignalEvents* events );
extern int  t_573_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_573_remove_marks( ACM_signals_NetMarking* marking );
extern void t_573_add_marks( ACM_signals_NetMarking* marking );
extern void t_573_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 574 - closer_3 */
extern int  t_574_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_574_events( ACM_signals_InputSignalEvents* events );
extern int  t_574_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_574_remove_marks( ACM_signals_NetMarking* marking );
extern void t_574_add_marks( ACM_signals_NetMarking* marking );
extern void t_574_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 575 - further_4 */
extern int  t_575_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_575_events( ACM_signals_InputSignalEvents* events );
extern int  t_575_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_575_remove_marks( ACM_signals_NetMarking* marking );
extern void t_575_add_marks( ACM_signals_NetMarking* marking );
extern void t_575_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 576 - closer_4 */
extern int  t_576_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_576_events( ACM_signals_InputSignalEvents* events );
extern int  t_576_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_576_remove_marks( ACM_signals_NetMarking* marking );
extern void t_576_add_marks( ACM_signals_NetMarking* marking );
extern void t_576_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 593 - closer_5 */
extern int  t_593_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_593_events( ACM_signals_InputSignalEvents* events );
extern int  t_593_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_593_remove_marks( ACM_signals_NetMarking* marking );
extern void t_593_add_marks( ACM_signals_NetMarking* marking );
extern void t_593_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 594 - further_5 */
extern int  t_594_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_594_events( ACM_signals_InputSignalEvents* events );
extern int  t_594_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_594_remove_marks( ACM_signals_NetMarking* marking );
extern void t_594_add_marks( ACM_signals_NetMarking* marking );
extern void t_594_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 595 - further_6 */
extern int  t_595_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_595_events( ACM_signals_InputSignalEvents* events );
extern int  t_595_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_595_remove_marks( ACM_signals_NetMarking* marking );
extern void t_595_add_marks( ACM_signals_NetMarking* marking );
extern void t_595_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 596 - closer_6 */
extern int  t_596_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_596_events( ACM_signals_InputSignalEvents* events );
extern int  t_596_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_596_remove_marks( ACM_signals_NetMarking* marking );
extern void t_596_add_marks( ACM_signals_NetMarking* marking );
extern void t_596_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 597 - further_7 */
extern int  t_597_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_597_events( ACM_signals_InputSignalEvents* events );
extern int  t_597_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_597_remove_marks( ACM_signals_NetMarking* marking );
extern void t_597_add_marks( ACM_signals_NetMarking* marking );
extern void t_597_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 598 - closer_7 */
extern int  t_598_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_598_events( ACM_signals_InputSignalEvents* events );
extern int  t_598_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_598_remove_marks( ACM_signals_NetMarking* marking );
extern void t_598_add_marks( ACM_signals_NetMarking* marking );
extern void t_598_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 615 - step_detect */
extern int  t_615_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_615_events( ACM_signals_InputSignalEvents* events );
extern int  t_615_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_615_remove_marks( ACM_signals_NetMarking* marking );
extern void t_615_add_marks( ACM_signals_NetMarking* marking );
extern void t_615_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 616 - no_step */
extern int  t_616_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_616_events( ACM_signals_InputSignalEvents* events );
extern int  t_616_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_616_remove_marks( ACM_signals_NetMarking* marking );
extern void t_616_add_marks( ACM_signals_NetMarking* marking );
extern void t_616_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 643 - change_ON */
extern int  t_643_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_643_events( ACM_signals_InputSignalEvents* events );
extern int  t_643_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_643_remove_marks( ACM_signals_NetMarking* marking );
extern void t_643_add_marks( ACM_signals_NetMarking* marking );
extern void t_643_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 651 - change_joyInChg */
extern int  t_651_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_651_events( ACM_signals_InputSignalEvents* events );
extern int  t_651_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_651_remove_marks( ACM_signals_NetMarking* marking );
extern void t_651_add_marks( ACM_signals_NetMarking* marking );
extern void t_651_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 652 - change_OFF */
extern int  t_652_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_652_events( ACM_signals_InputSignalEvents* events );
extern int  t_652_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_652_remove_marks( ACM_signals_NetMarking* marking );
extern void t_652_add_marks( ACM_signals_NetMarking* marking );
extern void t_652_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 673 - step_control */
extern int  t_673_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_673_events( ACM_signals_InputSignalEvents* events );
extern int  t_673_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_673_remove_marks( ACM_signals_NetMarking* marking );
extern void t_673_add_marks( ACM_signals_NetMarking* marking );
extern void t_673_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 685 - stop_joyInChg */
extern int  t_685_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_685_events( ACM_signals_InputSignalEvents* events );
extern int  t_685_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_685_remove_marks( ACM_signals_NetMarking* marking );
extern void t_685_add_marks( ACM_signals_NetMarking* marking );
extern void t_685_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 686 - stop_joyInChg */
extern int  t_686_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_686_events( ACM_signals_InputSignalEvents* events );
extern int  t_686_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_686_remove_marks( ACM_signals_NetMarking* marking );
extern void t_686_add_marks( ACM_signals_NetMarking* marking );
extern void t_686_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 694 - obstacle_control */
extern int  t_694_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_694_events( ACM_signals_InputSignalEvents* events );
extern int  t_694_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_694_remove_marks( ACM_signals_NetMarking* marking );
extern void t_694_add_marks( ACM_signals_NetMarking* marking );
extern void t_694_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 707 - move_B */
extern int  t_707_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_707_events( ACM_signals_InputSignalEvents* events );
extern int  t_707_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_707_remove_marks( ACM_signals_NetMarking* marking );
extern void t_707_add_marks( ACM_signals_NetMarking* marking );
extern void t_707_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 711 - stop_BackON */
extern int  t_711_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_711_events( ACM_signals_InputSignalEvents* events );
extern int  t_711_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_711_remove_marks( ACM_signals_NetMarking* marking );
extern void t_711_add_marks( ACM_signals_NetMarking* marking );
extern void t_711_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 712 - stop_FrontOFF */
extern int  t_712_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_712_events( ACM_signals_InputSignalEvents* events );
extern int  t_712_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_712_remove_marks( ACM_signals_NetMarking* marking );
extern void t_712_add_marks( ACM_signals_NetMarking* marking );
extern void t_712_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 713 - stop_joyInChg */
extern int  t_713_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_713_events( ACM_signals_InputSignalEvents* events );
extern int  t_713_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_713_remove_marks( ACM_signals_NetMarking* marking );
extern void t_713_add_marks( ACM_signals_NetMarking* marking );
extern void t_713_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 728 - stop_LeftON */
extern int  t_728_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_728_events( ACM_signals_InputSignalEvents* events );
extern int  t_728_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_728_remove_marks( ACM_signals_NetMarking* marking );
extern void t_728_add_marks( ACM_signals_NetMarking* marking );
extern void t_728_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 730 - stop_RightOFF */
extern int  t_730_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_730_events( ACM_signals_InputSignalEvents* events );
extern int  t_730_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_730_remove_marks( ACM_signals_NetMarking* marking );
extern void t_730_add_marks( ACM_signals_NetMarking* marking );
extern void t_730_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 731 - stop_joyInChg */
extern int  t_731_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_731_events( ACM_signals_InputSignalEvents* events );
extern int  t_731_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_731_remove_marks( ACM_signals_NetMarking* marking );
extern void t_731_add_marks( ACM_signals_NetMarking* marking );
extern void t_731_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 742 - move_R */
extern int  t_742_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_742_events( ACM_signals_InputSignalEvents* events );
extern int  t_742_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_742_remove_marks( ACM_signals_NetMarking* marking );
extern void t_742_add_marks( ACM_signals_NetMarking* marking );
extern void t_742_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 745 - stop_FrontBackON */
extern int  t_745_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_745_events( ACM_signals_InputSignalEvents* events );
extern int  t_745_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_745_remove_marks( ACM_signals_NetMarking* marking );
extern void t_745_add_marks( ACM_signals_NetMarking* marking );
extern void t_745_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 746 - stop_FrontBackON */
extern int  t_746_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_746_events( ACM_signals_InputSignalEvents* events );
extern int  t_746_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_746_remove_marks( ACM_signals_NetMarking* marking );
extern void t_746_add_marks( ACM_signals_NetMarking* marking );
extern void t_746_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 752 - stop_LeftRightON */
extern int  t_752_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_752_events( ACM_signals_InputSignalEvents* events );
extern int  t_752_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_752_remove_marks( ACM_signals_NetMarking* marking );
extern void t_752_add_marks( ACM_signals_NetMarking* marking );
extern void t_752_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 757 - stop_LeftRightON */
extern int  t_757_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_757_events( ACM_signals_InputSignalEvents* events );
extern int  t_757_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_757_remove_marks( ACM_signals_NetMarking* marking );
extern void t_757_add_marks( ACM_signals_NetMarking* marking );
extern void t_757_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 765 - step_control */
extern int  t_765_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_765_events( ACM_signals_InputSignalEvents* events );
extern int  t_765_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_765_remove_marks( ACM_signals_NetMarking* marking );
extern void t_765_add_marks( ACM_signals_NetMarking* marking );
extern void t_765_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 768 - step_control */
extern int  t_768_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_768_events( ACM_signals_InputSignalEvents* events );
extern int  t_768_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_768_remove_marks( ACM_signals_NetMarking* marking );
extern void t_768_add_marks( ACM_signals_NetMarking* marking );
extern void t_768_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 771 - move_F */
extern int  t_771_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_771_events( ACM_signals_InputSignalEvents* events );
extern int  t_771_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_771_remove_marks( ACM_signals_NetMarking* marking );
extern void t_771_add_marks( ACM_signals_NetMarking* marking );
extern void t_771_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 777 - move_L */
extern int  t_777_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_777_events( ACM_signals_InputSignalEvents* events );
extern int  t_777_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_777_remove_marks( ACM_signals_NetMarking* marking );
extern void t_777_add_marks( ACM_signals_NetMarking* marking );
extern void t_777_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 780 - obstacle_control */
extern int  t_780_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_780_events( ACM_signals_InputSignalEvents* events );
extern int  t_780_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_780_remove_marks( ACM_signals_NetMarking* marking );
extern void t_780_add_marks( ACM_signals_NetMarking* marking );
extern void t_780_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 783 - obstacle_control_2 */
extern int  t_783_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_783_events( ACM_signals_InputSignalEvents* events );
extern int  t_783_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_783_remove_marks( ACM_signals_NetMarking* marking );
extern void t_783_add_marks( ACM_signals_NetMarking* marking );
extern void t_783_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 786 - obstacle_control */
extern int  t_786_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_786_events( ACM_signals_InputSignalEvents* events );
extern int  t_786_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_786_remove_marks( ACM_signals_NetMarking* marking );
extern void t_786_add_marks( ACM_signals_NetMarking* marking );
extern void t_786_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 787 - obstacle_control_2 */
extern int  t_787_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_787_events( ACM_signals_InputSignalEvents* events );
extern int  t_787_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_787_remove_marks( ACM_signals_NetMarking* marking );
extern void t_787_add_marks( ACM_signals_NetMarking* marking );
extern void t_787_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 824 - up */
extern int  t_824_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_824_events( ACM_signals_InputSignalEvents* events );
extern int  t_824_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_824_remove_marks( ACM_signals_NetMarking* marking );
extern void t_824_add_marks( ACM_signals_NetMarking* marking );
extern void t_824_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 825 - down */
extern int  t_825_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_825_events( ACM_signals_InputSignalEvents* events );
extern int  t_825_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_825_remove_marks( ACM_signals_NetMarking* marking );
extern void t_825_add_marks( ACM_signals_NetMarking* marking );
extern void t_825_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 836 - up */
extern int  t_836_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_836_events( ACM_signals_InputSignalEvents* events );
extern int  t_836_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_836_remove_marks( ACM_signals_NetMarking* marking );
extern void t_836_add_marks( ACM_signals_NetMarking* marking );
extern void t_836_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 837 - down */
extern int  t_837_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_837_events( ACM_signals_InputSignalEvents* events );
extern int  t_837_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_837_remove_marks( ACM_signals_NetMarking* marking );
extern void t_837_add_marks( ACM_signals_NetMarking* marking );
extern void t_837_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 843 - up */
extern int  t_843_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_843_events( ACM_signals_InputSignalEvents* events );
extern int  t_843_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_843_remove_marks( ACM_signals_NetMarking* marking );
extern void t_843_add_marks( ACM_signals_NetMarking* marking );
extern void t_843_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 844 - down */
extern int  t_844_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_844_events( ACM_signals_InputSignalEvents* events );
extern int  t_844_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_844_remove_marks( ACM_signals_NetMarking* marking );
extern void t_844_add_marks( ACM_signals_NetMarking* marking );
extern void t_844_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 850 - down_1 */
extern int  t_850_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_850_events( ACM_signals_InputSignalEvents* events );
extern int  t_850_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_850_remove_marks( ACM_signals_NetMarking* marking );
extern void t_850_add_marks( ACM_signals_NetMarking* marking );
extern void t_850_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 851 - up_1 */
extern int  t_851_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_851_events( ACM_signals_InputSignalEvents* events );
extern int  t_851_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_851_remove_marks( ACM_signals_NetMarking* marking );
extern void t_851_add_marks( ACM_signals_NetMarking* marking );
extern void t_851_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 853 - down_1 */
extern int  t_853_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_853_events( ACM_signals_InputSignalEvents* events );
extern int  t_853_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_853_remove_marks( ACM_signals_NetMarking* marking );
extern void t_853_add_marks( ACM_signals_NetMarking* marking );
extern void t_853_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 854 - up_1 */
extern int  t_854_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_854_events( ACM_signals_InputSignalEvents* events );
extern int  t_854_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_854_remove_marks( ACM_signals_NetMarking* marking );
extern void t_854_add_marks( ACM_signals_NetMarking* marking );
extern void t_854_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 856 - down_1 */
extern int  t_856_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_856_events( ACM_signals_InputSignalEvents* events );
extern int  t_856_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_856_remove_marks( ACM_signals_NetMarking* marking );
extern void t_856_add_marks( ACM_signals_NetMarking* marking );
extern void t_856_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 857 - up_1 */
extern int  t_857_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_857_events( ACM_signals_InputSignalEvents* events );
extern int  t_857_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_857_remove_marks( ACM_signals_NetMarking* marking );
extern void t_857_add_marks( ACM_signals_NetMarking* marking );
extern void t_857_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 870 - increase_assist_1 */
extern int  t_870_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_870_events( ACM_signals_InputSignalEvents* events );
extern int  t_870_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_870_remove_marks( ACM_signals_NetMarking* marking );
extern void t_870_add_marks( ACM_signals_NetMarking* marking );
extern void t_870_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 873 - increase_assist_2 */
extern int  t_873_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_873_events( ACM_signals_InputSignalEvents* events );
extern int  t_873_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_873_remove_marks( ACM_signals_NetMarking* marking );
extern void t_873_add_marks( ACM_signals_NetMarking* marking );
extern void t_873_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 876 - increase_assist_3 */
extern int  t_876_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_876_events( ACM_signals_InputSignalEvents* events );
extern int  t_876_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_876_remove_marks( ACM_signals_NetMarking* marking );
extern void t_876_add_marks( ACM_signals_NetMarking* marking );
extern void t_876_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 879 - decrease_assist_3 */
extern int  t_879_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_879_events( ACM_signals_InputSignalEvents* events );
extern int  t_879_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_879_remove_marks( ACM_signals_NetMarking* marking );
extern void t_879_add_marks( ACM_signals_NetMarking* marking );
extern void t_879_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 880 - decrease_assist_2 */
extern int  t_880_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_880_events( ACM_signals_InputSignalEvents* events );
extern int  t_880_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_880_remove_marks( ACM_signals_NetMarking* marking );
extern void t_880_add_marks( ACM_signals_NetMarking* marking );
extern void t_880_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 881 - decrease_assist_1 */
extern int  t_881_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_881_events( ACM_signals_InputSignalEvents* events );
extern int  t_881_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_881_remove_marks( ACM_signals_NetMarking* marking );
extern void t_881_add_marks( ACM_signals_NetMarking* marking );
extern void t_881_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 888 - horn_ON_step */
extern int  t_888_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_888_events( ACM_signals_InputSignalEvents* events );
extern int  t_888_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_888_remove_marks( ACM_signals_NetMarking* marking );
extern void t_888_add_marks( ACM_signals_NetMarking* marking );
extern void t_888_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 895 - horn_OFF_joyInChg */
extern int  t_895_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_895_events( ACM_signals_InputSignalEvents* events );
extern int  t_895_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_895_remove_marks( ACM_signals_NetMarking* marking );
extern void t_895_add_marks( ACM_signals_NetMarking* marking );
extern void t_895_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
/* Transition 901 - horn_ON_obstacle */
extern int  t_901_enabled( ACM_signals_NetMarking* prev, ACM_signals_NetMarking* avail );
extern int  t_901_events( ACM_signals_InputSignalEvents* events );
extern int  t_901_guards( ACM_signals_NetMarking* marking, ACM_signals_InputSignals* inputs, ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* ev_out );
extern void t_901_remove_marks( ACM_signals_NetMarking* marking );
extern void t_901_add_marks( ACM_signals_NetMarking* marking );
extern void t_901_generate_output_events( ACM_signals_OutputSignalEvents* ev_out );
extern void ACM_signals_GenerateInputSignalEvents( ACM_signals_InputSignals *old_values, ACM_signals_InputSignals *new_values, ACM_signals_InputSignalEvents *events );

extern void ACM_signals_GenerateEventOutputSignals( ACM_signals_OutputSignalEvents *events, ACM_signals_EventOutputSignals *signals );

extern void ACM_signals_GenerateTransitionActionOutputSignals( ACM_signals_TransitionFiring *tfired, ACM_signals_NetMarking *marking, ACM_signals_EventOutputSignals *signals );

extern void ACM_signals_GeneratePlaceOutputSignals( ACM_signals_NetMarking *marking, ACM_signals_InputSignals *inputs, ACM_signals_PlaceOutputSignals *place_out, ACM_signals_EventOutputSignals *ev_out );

extern void ACM_signals_ExecutionStep( ACM_signals_NetMarking *prev_marking, ACM_signals_InputSignals *inputs, ACM_signals_InputSignals *prev_in, ACM_signals_PlaceOutputSignals *place_out, ACM_signals_EventOutputSignals *ev_out );

extern void ACM_signals_InitializeIO();
extern void ACM_signals_GetInputSignals( ACM_signals_InputSignals* inputs, ACM_signals_InputSignalEvents* events );
extern void ACM_signals_PutOutputSignals( ACM_signals_PlaceOutputSignals* place_out, ACM_signals_EventOutputSignals* event_out, ACM_signals_OutputSignalEvents* events );
extern void ACM_signals_LoopDelay();
extern int ACM_signals_FinishExecution( ACM_signals_NetMarking* marking );

extern ACM_signals_NetMarking* get_ACM_signals_NetMarking();
extern ACM_signals_InputSignals* get_ACM_signals_InputSignals();
extern ACM_signals_PlaceOutputSignals* get_ACM_signals_PlaceOutputSignals();
extern ACM_signals_EventOutputSignals* get_ACM_signals_EventOutputSignals();
extern ACM_signals_TransitionFiring* get_ACM_signals_TransitionFiring();

#ifdef __cplusplus
};
#endif


#endif
